{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 98452,
          "sha512": "841fd758868a950c0d6e44c4922424ee9ffc4ce49aae4f3ac962c091fb41896ef95f8859a5b3deca727ef65a803c58c65d4964c2145721ea01bc74b0e719e1e9",
          "sha256": "0e9b811b058fdfe32712226d36e58763adea5b8010527bb9be0353221b5a7b12",
          "sha1": "619196a44f346a4ebbdafb63410f8b6a0672b1b9",
          "md5": "889474764dd2ea6e8fffa1e8651209f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 98452,
          "sha512": "841fd758868a950c0d6e44c4922424ee9ffc4ce49aae4f3ac962c091fb41896ef95f8859a5b3deca727ef65a803c58c65d4964c2145721ea01bc74b0e719e1e9",
          "sha256": "0e9b811b058fdfe32712226d36e58763adea5b8010527bb9be0353221b5a7b12",
          "sha1": "619196a44f346a4ebbdafb63410f8b6a0672b1b9",
          "md5": "889474764dd2ea6e8fffa1e8651209f8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_release-1.0-sources.jar",
          "url": "video_player_android_release-1.0-sources.jar",
          "size": 26931,
          "sha512": "ad5734295e3d2a430d515204017864b81e6c2bd974569e4ce2a12c85b290989af16e745c8b1dda6562dc7cd0cd44a39e34b5b3b36c9b0422a9568fad6332998e",
          "sha256": "e5ca87c8679e3f950902fa2d978806ff357ee80ffcd04416fc7c5a2a21000970",
          "sha1": "ff1a68e54d388b29380c02c515cb3c5779b1c02b",
          "md5": "4fab281c6eccd49db09d5aa9b4d36f4c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_release-1.0-javadoc.jar",
          "url": "video_player_android_release-1.0-javadoc.jar",
          "size": 468722,
          "sha512": "1e09e954070a4e078e155ec8756671eefcff9a5d9724fe8dcaabb2355cebd91c95ca25b5525c44e41da7839a00cd31118d46a11a1ef6828a75e7558e56b20ecf",
          "sha256": "05a2fd2ad4070a132c3ffd9183d9e9d251653e05086f4ae33758389f9296b805",
          "sha1": "ac6bfea8aace466b8a5e76ba0c89c5fb114b4153",
          "md5": "eb67c0462eae942cb25fce51cd56ce59"
        }
      ]
    }
  ]
}
