{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.videoplayer",
    "module": "video_player_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 98143,
          "sha512": "f17b614367bea4593de18f2f682e56968897b2960e9a7296c87955ef834c3eeba8f6c84e86ab77820edcbb593cce60b086f93dd21dc98cbe5ccb584e0a37441e",
          "sha256": "6830f5a9124ead10c2fc2930453a2ece82af8910a44fc3ac3eac1ff27b3d408d",
          "sha1": "924397e070f2b7b8a107481bf1ca087b3d1b0f1e",
          "md5": "0ecb3e7215c8ae870732948acc3e3cf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-hls",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-dash",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-rtsp",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "androidx.media3",
          "module": "media3-exoplayer-smoothstreaming",
          "version": {
            "requires": "1.9.2"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "video_player_android_release-1.0.aar",
          "url": "video_player_android_release-1.0.aar",
          "size": 98143,
          "sha512": "f17b614367bea4593de18f2f682e56968897b2960e9a7296c87955ef834c3eeba8f6c84e86ab77820edcbb593cce60b086f93dd21dc98cbe5ccb584e0a37441e",
          "sha256": "6830f5a9124ead10c2fc2930453a2ece82af8910a44fc3ac3eac1ff27b3d408d",
          "sha1": "924397e070f2b7b8a107481bf1ca087b3d1b0f1e",
          "md5": "0ecb3e7215c8ae870732948acc3e3cf4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_release-1.0-sources.jar",
          "url": "video_player_android_release-1.0-sources.jar",
          "size": 26931,
          "sha512": "ad5734295e3d2a430d515204017864b81e6c2bd974569e4ce2a12c85b290989af16e745c8b1dda6562dc7cd0cd44a39e34b5b3b36c9b0422a9568fad6332998e",
          "sha256": "e5ca87c8679e3f950902fa2d978806ff357ee80ffcd04416fc7c5a2a21000970",
          "sha1": "ff1a68e54d388b29380c02c515cb3c5779b1c02b",
          "md5": "4fab281c6eccd49db09d5aa9b4d36f4c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "video_player_android_release-1.0-javadoc.jar",
          "url": "video_player_android_release-1.0-javadoc.jar",
          "size": 468710,
          "sha512": "fe084a91c23ecca15c7d9737e9ba520746bb2986486eb35b3061870f39853e588d7df9548c07b68741b50f5267ea774efddc24c898a4c6ef765049941314be92",
          "sha256": "a09a92cbd1ff67ab89ec32dadc13852e13c2a55567657eab5b2600f38a751c9b",
          "sha1": "897aef4d65a402d1aeb9403f5a2dd28a1704181f",
          "md5": "f30f38278696e5e9132a7fe415a1026e"
        }
      ]
    }
  ]
}
