{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 25067,
          "sha512": "861c9a39cae3a5f7b950fc2846c8a55786ea5910d8888eb9154391807603259c13a5c6aab42b044076cd68728bc5126e5b084e33d0d7f51852afcef3475cdd25",
          "sha256": "1459f986e5ec6fabcc523369156a841ecec866f81004577fc11783b7dfcd4ec5",
          "sha1": "e57d4e8d9ad24bf549b6e20174c44026f365f65a",
          "md5": "d71f14cc5054c9ad0c365beef174742c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 25067,
          "sha512": "861c9a39cae3a5f7b950fc2846c8a55786ea5910d8888eb9154391807603259c13a5c6aab42b044076cd68728bc5126e5b084e33d0d7f51852afcef3475cdd25",
          "sha256": "1459f986e5ec6fabcc523369156a841ecec866f81004577fc11783b7dfcd4ec5",
          "sha1": "e57d4e8d9ad24bf549b6e20174c44026f365f65a",
          "md5": "d71f14cc5054c9ad0c365beef174742c"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-sources.jar",
          "url": "flutter_secure_storage_release-1.0-sources.jar",
          "size": 12534,
          "sha512": "fcdbec471d1020aca7debb4980e3cea0b149e8b8580c5fb3b2c21ca8576ba704f7169a83c62db1c1ded8560f437ffbee69f49a5812d36b452bbf0f6930d27fe6",
          "sha256": "b1bca772397453d700fe173e49d629cdfc2a735732389f1ae6898b147a934087",
          "sha1": "19c22aced34c08b86837d9bcb1039e715f573657",
          "md5": "0bf72f214670f698fed4573890e558e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-javadoc.jar",
          "url": "flutter_secure_storage_release-1.0-javadoc.jar",
          "size": 307677,
          "sha512": "79b25f506f3027f3c4c26bef8eb2aa076d54fdf4cf6ef7f6816dd3c6a7dde45b3cae3261861b748377a755037158dcc37a07feaf79d21c608fdcceaf1cc4a3d8",
          "sha256": "0204cccc46dbd729df966f42304a8d229f721a86649e077964298bc043bdbf31",
          "sha1": "5be149decdd3aac0ca1d5308677ebf8e3b2787c3",
          "md5": "79a506da132c9049e95a45d1c8208253"
        }
      ]
    }
  ]
}
