{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 24964,
          "sha512": "e950f14c06e90a365af28f68cb073d9827f0fab6cca480434bf6203082b74f4b30c92ee7aa9a7c27504a13702e9543814653d71eb4b920ecfc7862237f063e0b",
          "sha256": "23eecce9bea33965ea0798c898367b1776ebe21e3c2bbbf5092b761752fa3420",
          "sha1": "f073b872d93721d241fe6ea9952bf9a43d0385cc",
          "md5": "c646cad6a22724e6d2c0ec6f16f5506e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.security",
          "module": "security-crypto",
          "version": {
            "requires": "1.1.0-alpha06"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 24964,
          "sha512": "e950f14c06e90a365af28f68cb073d9827f0fab6cca480434bf6203082b74f4b30c92ee7aa9a7c27504a13702e9543814653d71eb4b920ecfc7862237f063e0b",
          "sha256": "23eecce9bea33965ea0798c898367b1776ebe21e3c2bbbf5092b761752fa3420",
          "sha1": "f073b872d93721d241fe6ea9952bf9a43d0385cc",
          "md5": "c646cad6a22724e6d2c0ec6f16f5506e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-sources.jar",
          "url": "flutter_secure_storage_release-1.0-sources.jar",
          "size": 12534,
          "sha512": "fcdbec471d1020aca7debb4980e3cea0b149e8b8580c5fb3b2c21ca8576ba704f7169a83c62db1c1ded8560f437ffbee69f49a5812d36b452bbf0f6930d27fe6",
          "sha256": "b1bca772397453d700fe173e49d629cdfc2a735732389f1ae6898b147a934087",
          "sha1": "19c22aced34c08b86837d9bcb1039e715f573657",
          "md5": "0bf72f214670f698fed4573890e558e7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-javadoc.jar",
          "url": "flutter_secure_storage_release-1.0-javadoc.jar",
          "size": 307718,
          "sha512": "b8aa0328b31eda843d85db2f52eb1164105a86eaa6ef5d8a1813be7b8267650d374345f23c17ba850f175043bee3c70d34cec58cb45c0978669195ddb2d9766b",
          "sha256": "b0750978d133ec65c79ed6e773c36ca3b22cf2c7fd8978e0ece76bf79c767f7d",
          "sha1": "443ed7c91420b0648420cee431a2e4ff693702fa",
          "md5": "733528a8408e559d074dd2fbaa30152e"
        }
      ]
    }
  ]
}
