{
  "formatVersion": "1.1",
  "component": {
    "group": "com.it_nomads.fluttersecurestorage",
    "module": "flutter_secure_storage_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 80579,
          "sha512": "fdfc872654b3acd836bb201c8a452e9616874b687379dcb176ab7368d4c987bfeaee8ea970ae497e9566fafbb6dce20033753ac7de370ecb1a08b61d3c9d28e7",
          "sha256": "ec5e3f58cfcb4501cb0964861fc079214c7eb9935fd1a0eac4a0f7ebcaf0a008",
          "sha1": "329edd211ed29c35dcc36475245bb92ba820f77e",
          "md5": "a8287c2988fcb280958299455a6eed61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "com.google.crypto.tink",
          "module": "tink-android",
          "version": {
            "requires": "1.19.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0.aar",
          "url": "flutter_secure_storage_release-1.0.aar",
          "size": 80579,
          "sha512": "fdfc872654b3acd836bb201c8a452e9616874b687379dcb176ab7368d4c987bfeaee8ea970ae497e9566fafbb6dce20033753ac7de370ecb1a08b61d3c9d28e7",
          "sha256": "ec5e3f58cfcb4501cb0964861fc079214c7eb9935fd1a0eac4a0f7ebcaf0a008",
          "sha1": "329edd211ed29c35dcc36475245bb92ba820f77e",
          "md5": "a8287c2988fcb280958299455a6eed61"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-sources.jar",
          "url": "flutter_secure_storage_release-1.0-sources.jar",
          "size": 40762,
          "sha512": "daaf33723538bec343366b74b9bdea6a7d77806e08bddc0a8f599581070dfad6a3bdf26f295a6aeee0690a2b2eec98568be2aea964eb8fc3015403de9aa30d57",
          "sha256": "dcae543b4ad127eeda9b77ba74ba293be96d799f3fb8cfcaf081690815aa0aff",
          "sha1": "eb7ea6a0db1c8d724dad3874b6ead692e40cf44f",
          "md5": "30c1a5d2618b53fea0b6d49acc2fb3e8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_secure_storage_release-1.0-javadoc.jar",
          "url": "flutter_secure_storage_release-1.0-javadoc.jar",
          "size": 353824,
          "sha512": "419bdc9a4c9bd3c2b545d2d0092002a1e1eeac266efd3a4a22947cc08ef6ab9e063ac6f8aa4afb99b5ab6626312af3774f623ced353498de16709d93be523bf8",
          "sha256": "79077db39d801bf08f828e0adc7c7e42fd71b7ca77d5194d50a7936aebdff3c2",
          "sha1": "fb4c724e0ccd06b7a6118458dbe6acdb9eb010d6",
          "md5": "5998b70d945db819a469caa5965c87e6"
        }
      ]
    }
  ]
}
