{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.33-test.342",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.33-test.342"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.33-test.342.aar",
          "url": "android_release-0.1.33-test.342.aar",
          "size": 1440670,
          "sha512": "798b40fc66f8a905f3113d690b204f642341e5d8f1415af4b51c69235d2d96060b2216a6fad12475bc6f56bdf308d39266033549da820d45766a6df950475720",
          "sha256": "f894c85c37c8620fe521c6843744551b016455c3076ebf6a33e4045c6224e087",
          "sha1": "ca7865f77ff06847b1a292dac9b77741995e2d2e",
          "md5": "2567f88a6b424d509e7606e2dd463be6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.33-test.342"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.33-test.342.aar",
          "url": "android_release-0.1.33-test.342.aar",
          "size": 1440670,
          "sha512": "798b40fc66f8a905f3113d690b204f642341e5d8f1415af4b51c69235d2d96060b2216a6fad12475bc6f56bdf308d39266033549da820d45766a6df950475720",
          "sha256": "f894c85c37c8620fe521c6843744551b016455c3076ebf6a33e4045c6224e087",
          "sha1": "ca7865f77ff06847b1a292dac9b77741995e2d2e",
          "md5": "2567f88a6b424d509e7606e2dd463be6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.33-test.342-sources.jar",
          "url": "android_release-0.1.33-test.342-sources.jar",
          "size": 370362,
          "sha512": "ca040ce2e7be5a1ba57dc6bd4079dc384374e6e89e7b1e14bb26694f68dac6acf9f62e2e5b4d1247449f067aa298f4494c7468162e3e915fb06154f9a490ebd2",
          "sha256": "b24faf148d4a2e6c36bf91ca7df547c4b2d8d065c178b6cd33dfd1dabd732aac",
          "sha1": "cf3327de68b536d1196c94ed49de61d79b434ed3",
          "md5": "93e4ca3caec3266dacf97c31149ea244"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.33-test.342-javadoc.jar",
          "url": "android_release-0.1.33-test.342-javadoc.jar",
          "size": 2414709,
          "sha512": "53784c493724a5092d8b4ba41456323eaaddcbc3de1ff028584df3ddad09d3e8358cc4c1c248f55c49c8d548d389b8eee8dca0150aeb16a2b7c4b74c331d2d8b",
          "sha256": "88da19d4a4bb8f0d5c1f209945c0f2f3456dbeeeeecbebe139a3dda0d4269f74",
          "sha1": "30f690e13493579ef33fd447de0210d82e323e56",
          "md5": "3328559ca9c15e878cdfa99a9f86b5d0"
        }
      ]
    }
  ]
}