{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.42-test.352",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.42-test.352"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.42-test.352.aar",
          "url": "android_release-0.1.42-test.352.aar",
          "size": 1493337,
          "sha512": "00e5d941d92fa1eff55fd2a68e4cf6d5822875cfdd507813a01e1d29cd693a5cc3b9f29358148916d18e536959388734a874b483cad67f40927cd07f1d40fee1",
          "sha256": "ff60e9150646de879b0276dbccf385eab548bbf3a748e75ac72bb2591870efac",
          "sha1": "5021398d061d3aee2cf3e39b7b29cae80f207639",
          "md5": "eeac167ad8a0fab343f70c728e7498f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.42-test.352"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.42-test.352.aar",
          "url": "android_release-0.1.42-test.352.aar",
          "size": 1493337,
          "sha512": "00e5d941d92fa1eff55fd2a68e4cf6d5822875cfdd507813a01e1d29cd693a5cc3b9f29358148916d18e536959388734a874b483cad67f40927cd07f1d40fee1",
          "sha256": "ff60e9150646de879b0276dbccf385eab548bbf3a748e75ac72bb2591870efac",
          "sha1": "5021398d061d3aee2cf3e39b7b29cae80f207639",
          "md5": "eeac167ad8a0fab343f70c728e7498f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.42-test.352-sources.jar",
          "url": "android_release-0.1.42-test.352-sources.jar",
          "size": 389955,
          "sha512": "8543d23faf4ba1f8a142de41bc316a5a3b53c5ad8ec0612dc20cde7a0c6b2abc921ce6489a32fcb3f84888ae58221f6f8134e1f8863ceb23b863d71c6409865c",
          "sha256": "fcb207c610cb1cddfd13f2479c852cc82193699cb5cf02811caceee5cd0bd023",
          "sha1": "d9f6676a16f2bf7928b418e26f5bf9f6a51ca322",
          "md5": "80b3e806593e3e11ef0624296b3b8d54"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.42-test.352-javadoc.jar",
          "url": "android_release-0.1.42-test.352-javadoc.jar",
          "size": 2474119,
          "sha512": "1f82ea1b7b387b23f4a22273041cab2124db2353cfb10577e7c6093e36d94a9f1b049f2b72674067d0a637609811b80b36acd189ad7555ebc82ab4b1fd89d6cf",
          "sha256": "9ac57c6d5e07e789130a5c4af65b248f894bb752800152b1aae6434066522e17",
          "sha1": "217b2e1fb13439c5135a2ccd79bd6fda000482b1",
          "md5": "a11cd350599b2967b5c9e8b7f2364fe3"
        }
      ]
    }
  ]
}