{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.12.aar",
          "url": "android_release-0.1.12.aar",
          "size": 1223831,
          "sha512": "39379e9379c482aa185121d9f9be21306b2c81177edde9dc0fc080d55ead4b697e4c9fe364ab5601390b95f2338b72efd5fe79c1443716857cd9fdc600aa78ea",
          "sha256": "8a56f9c6ed6f6274603a97c58ab4e9bb6e7fcfc509484f5adf87dc8c8c2f9a4b",
          "sha1": "5e16c7f15d543ced7946cfca5dd2e5df56053fdb",
          "md5": "debf5725eb22d6e70e479a66bc912c24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.12.aar",
          "url": "android_release-0.1.12.aar",
          "size": 1223831,
          "sha512": "39379e9379c482aa185121d9f9be21306b2c81177edde9dc0fc080d55ead4b697e4c9fe364ab5601390b95f2338b72efd5fe79c1443716857cd9fdc600aa78ea",
          "sha256": "8a56f9c6ed6f6274603a97c58ab4e9bb6e7fcfc509484f5adf87dc8c8c2f9a4b",
          "sha1": "5e16c7f15d543ced7946cfca5dd2e5df56053fdb",
          "md5": "debf5725eb22d6e70e479a66bc912c24"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.12-sources.jar",
          "url": "android_release-0.1.12-sources.jar",
          "size": 311531,
          "sha512": "2ea65c75e7be5d45ef211803de58b1ca9e9d81f80d46d692bd4df30c56d05972b3e5c7d8727ae02516c8107e8242cfeb027566c1b75241fad54e0fb03ca567cf",
          "sha256": "45aaa950ac81005c7d1c31341317bb8c8ca7c913aabc923f7453f1edd60208fc",
          "sha1": "3884ee86ffd06e315829059fa3608914535d8107",
          "md5": "119652fbfae27c25fa0bd2423c62aec1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.12-javadoc.jar",
          "url": "android_release-0.1.12-javadoc.jar",
          "size": 2105090,
          "sha512": "a19e75a4079acb9f5d3c701c7d863344dba9808ad5d956d79fcc3544855e1cd8bf31f31391c04d6e94008719b44c08d57ab39e10fa8cdbcfff5aeba3837e4daf",
          "sha256": "3fd6a15fed75b445d1f79a245bfb972cff4d1523baac9b5f7e22b39b84500ab0",
          "sha1": "21d479c2d861f605f0d2a30904a23c73db696cf4",
          "md5": "b6cb06657fb09dbb044bce4a00d65313"
        }
      ]
    }
  ]
}