{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.12",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.12.aar",
          "url": "android_release-0.1.12.aar",
          "size": 1137973,
          "sha512": "fe76f273e8d854678d33371eac7e713335bae3c87f7edc663e49b10be9bc1eb8f6eb6464c7c220962b6484744a2fc5a03279744a38b2c1dc62ec5b5eaa4187d8",
          "sha256": "645988543de3cc56598f5812cd0ad7d371bf784730ef8664c067e3a1aadb4b38",
          "sha1": "a06ec85b7aaab6f145ae006b596746c67101d98c",
          "md5": "970f856f9e48f6fbe370c5db3a03a509"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.12"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.12.aar",
          "url": "android_release-0.1.12.aar",
          "size": 1137973,
          "sha512": "fe76f273e8d854678d33371eac7e713335bae3c87f7edc663e49b10be9bc1eb8f6eb6464c7c220962b6484744a2fc5a03279744a38b2c1dc62ec5b5eaa4187d8",
          "sha256": "645988543de3cc56598f5812cd0ad7d371bf784730ef8664c067e3a1aadb4b38",
          "sha1": "a06ec85b7aaab6f145ae006b596746c67101d98c",
          "md5": "970f856f9e48f6fbe370c5db3a03a509"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.12-sources.jar",
          "url": "android_release-0.1.12-sources.jar",
          "size": 285059,
          "sha512": "6891487492ef51e1acf1c77979d6ed70e260d8a92d92bfa8ff4132879f4b8f29f9d817c9e3fd9afa832ab8572daa46c15bfefa9b939e34976bac248001a69ff0",
          "sha256": "4435ee2c799feb1a55e3d2dcbfa3009181a136ab6a049ce50aa1735d51d29358",
          "sha1": "541da5f232d79a93696dc62950582e0ac648cc99",
          "md5": "4917215dce43dea00afbad780aaa8a68"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.12-javadoc.jar",
          "url": "android_release-0.1.12-javadoc.jar",
          "size": 2026085,
          "sha512": "c91289139708c36d20eecdeaef11e66a83ebdd271f40e37ded08b7ef7b427a3508855bd97942cf33a4446927f37bb794c2ae7c1d09124696819596d9e51c14c3",
          "sha256": "752082a120e63eb76d45e3a00b44235ee5180971902d26166ab0dc933ca26c41",
          "sha1": "c1add0bfb2149fe9a8344f73ab89be7fed702692",
          "md5": "3929485e7d9bd4f4b4a74d1c9fdb7567"
        }
      ]
    }
  ]
}