{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.wakelock",
    "module": "wakelock_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_release-1.0.aar",
          "url": "wakelock_plus_release-1.0.aar",
          "size": 17929,
          "sha512": "f6770f83559074553e5c5a53552e8c7e1e164fc7db0c9bf3bcc20d186ebdb894328c047a71f65f3c1a80cbab4303293d084ccf0d34876a8273246e6aa7803218",
          "sha256": "0904bccb8d5e631d0e2b061a21fc87620d0a03cba77ed8c2d8fb298352f889bc",
          "sha1": "63910da797515613ef4c7cb81e8a38d78c2ea3ba",
          "md5": "f2ee4aaef404b5d81e9af7db52ad1ddb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_release-1.0.aar",
          "url": "wakelock_plus_release-1.0.aar",
          "size": 17929,
          "sha512": "f6770f83559074553e5c5a53552e8c7e1e164fc7db0c9bf3bcc20d186ebdb894328c047a71f65f3c1a80cbab4303293d084ccf0d34876a8273246e6aa7803218",
          "sha256": "0904bccb8d5e631d0e2b061a21fc87620d0a03cba77ed8c2d8fb298352f889bc",
          "sha1": "63910da797515613ef4c7cb81e8a38d78c2ea3ba",
          "md5": "f2ee4aaef404b5d81e9af7db52ad1ddb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wakelock_plus_release-1.0-sources.jar",
          "url": "wakelock_plus_release-1.0-sources.jar",
          "size": 3916,
          "sha512": "359767be2b797d98373f6871328829009d6022867726334813b38969564f029dc5b1aeea9e1e28a5a6031c1a261b5d2e135d26783a33ac117f587f0196df6e29",
          "sha256": "fd5b4a6f7f39aafb97d6d8992d3dd22e7349b4be8609b38d9f9abf3c352a01f1",
          "sha1": "aa81e2a7321590905f0114b14d7c1c6b63922989",
          "md5": "e818359f078b4a104e6aa81dc9b61f93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wakelock_plus_release-1.0-javadoc.jar",
          "url": "wakelock_plus_release-1.0-javadoc.jar",
          "size": 310231,
          "sha512": "3fb7c4d762b193a2568d922594110c1e093d557c473e3fe0dc31d62fe3d125b88a995543d18226ad415404e60f09fe4ef32d0c78bc3a6e2a19481b24c7b6ee16",
          "sha256": "4320ea626c0aa54c583b070665477b6e0601092a23dbda29b50d3a980dff6a9e",
          "sha1": "f3aa3a1da1d1b724a46bb0377c39e5eb6679c969",
          "md5": "77239cee001296b6d7ab91b01be16fd6"
        }
      ]
    }
  ]
}
