{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.wakelock",
    "module": "wakelock_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_release-1.0.aar",
          "url": "wakelock_plus_release-1.0.aar",
          "size": 17929,
          "sha512": "f6770f83559074553e5c5a53552e8c7e1e164fc7db0c9bf3bcc20d186ebdb894328c047a71f65f3c1a80cbab4303293d084ccf0d34876a8273246e6aa7803218",
          "sha256": "0904bccb8d5e631d0e2b061a21fc87620d0a03cba77ed8c2d8fb298352f889bc",
          "sha1": "63910da797515613ef4c7cb81e8a38d78c2ea3ba",
          "md5": "f2ee4aaef404b5d81e9af7db52ad1ddb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "wakelock_plus_release-1.0.aar",
          "url": "wakelock_plus_release-1.0.aar",
          "size": 17929,
          "sha512": "f6770f83559074553e5c5a53552e8c7e1e164fc7db0c9bf3bcc20d186ebdb894328c047a71f65f3c1a80cbab4303293d084ccf0d34876a8273246e6aa7803218",
          "sha256": "0904bccb8d5e631d0e2b061a21fc87620d0a03cba77ed8c2d8fb298352f889bc",
          "sha1": "63910da797515613ef4c7cb81e8a38d78c2ea3ba",
          "md5": "f2ee4aaef404b5d81e9af7db52ad1ddb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wakelock_plus_release-1.0-sources.jar",
          "url": "wakelock_plus_release-1.0-sources.jar",
          "size": 3916,
          "sha512": "359767be2b797d98373f6871328829009d6022867726334813b38969564f029dc5b1aeea9e1e28a5a6031c1a261b5d2e135d26783a33ac117f587f0196df6e29",
          "sha256": "fd5b4a6f7f39aafb97d6d8992d3dd22e7349b4be8609b38d9f9abf3c352a01f1",
          "sha1": "aa81e2a7321590905f0114b14d7c1c6b63922989",
          "md5": "e818359f078b4a104e6aa81dc9b61f93"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "wakelock_plus_release-1.0-javadoc.jar",
          "url": "wakelock_plus_release-1.0-javadoc.jar",
          "size": 310181,
          "sha512": "bd1585f679370f1203a34c4a07de1b462049fc5040d781cbeed6a646b05675c81bf4067aaafb489a121acc1d35517d9e728b5dda5992d8d38f69518ef337bc39",
          "sha256": "6405b0b5e4114cc702a170a4760e9da636b25d62b1faae4225c8682f8cb97a4d",
          "sha1": "99be376797c7955f2d427a723982af4ee90688e3",
          "md5": "ab6834d8a1544c73b0f6304039877e19"
        }
      ]
    }
  ]
}
