{
  "formatVersion": "1.1",
  "component": {
    "group": "com.tekartik.sqflite",
    "module": "sqflite_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-1.0.aar",
          "url": "sqflite_android_release-1.0.aar",
          "size": 42986,
          "sha512": "a3b861d06f741b2e7802dd916929e16d1b3314f0624f860f66fd1dcfa506b7185919ae73dad0ca9dbfe8ab68554e19c581f7eedc18048ae8c3f06d12528037a2",
          "sha256": "d38c43fdecfd7aa76cf897a683af11041ae8b85f43374caa9fc022f7f634d5e0",
          "sha1": "fe0774cad4b4984c40b1918db7917e828675854d",
          "md5": "053b7ff958728c6431090189fc704d0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "sqflite_android_release-1.0.aar",
          "url": "sqflite_android_release-1.0.aar",
          "size": 42986,
          "sha512": "a3b861d06f741b2e7802dd916929e16d1b3314f0624f860f66fd1dcfa506b7185919ae73dad0ca9dbfe8ab68554e19c581f7eedc18048ae8c3f06d12528037a2",
          "sha256": "d38c43fdecfd7aa76cf897a683af11041ae8b85f43374caa9fc022f7f634d5e0",
          "sha1": "fe0774cad4b4984c40b1918db7917e828675854d",
          "md5": "053b7ff958728c6431090189fc704d0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-1.0-sources.jar",
          "url": "sqflite_android_release-1.0-sources.jar",
          "size": 23748,
          "sha512": "79a18e8544303c175a5518d48dc0d23a617f6da7f5ddf699a7e94e154c1a221a1182d6b22363d34103e63d7e17decb835bdc2e3e92bfe0d08b1be7349ecc3847",
          "sha256": "7c4ef41dcd75693d0abddc88b3ba5c2fd30c31ee71155462d81055d982095868",
          "sha1": "8b554a039e5de13b3998bf9f2a1ef11cda40c2f1",
          "md5": "54e2ffa57d01fe69ac670dda7fb4b5f3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "sqflite_android_release-1.0-javadoc.jar",
          "url": "sqflite_android_release-1.0-javadoc.jar",
          "size": 339876,
          "sha512": "2c4208acf23441b77c92b91b99fa4e39c86e1b73233655daa492eaaa9b44ab5eb968177e869670acb227ff6c75f06fe344049d62d992f171b15066ce6c247024",
          "sha256": "2582d8e993dadf195efe48e7736630f92edd9d391033371346203c9e7f1071e8",
          "sha1": "b22b3b222fd338f4a1168b9f0dcacb5bd04a044a",
          "md5": "89c084e3686a8dbd7b9e7b3a08929012"
        }
      ]
    }
  ]
}
