{
  "formatVersion": "1.1",
  "component": {
    "group": "com.github.dart_lang.jni",
    "module": "jni_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-1.0.aar",
          "url": "jni_release-1.0.aar",
          "size": 104799,
          "sha512": "afcbba743f927cea029c2d04cc450cf90b461fba6cb13a6c7fe3d238a5fa029677c72fc5008126023643dfd760f6e630f38df320c7c318235c8500b0545abbc5",
          "sha256": "d4f8f37ae3f0d11d5a0103b989ae916e52b8b114cf46da4d37c5b8f87c59c1a5",
          "sha1": "d35a0bd69f3734e9e2f13ff06a87bba4bc07bb64",
          "md5": "35986f81970bc1cdaa4fd9b8bf5146c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "jni_release-1.0.aar",
          "url": "jni_release-1.0.aar",
          "size": 104799,
          "sha512": "afcbba743f927cea029c2d04cc450cf90b461fba6cb13a6c7fe3d238a5fa029677c72fc5008126023643dfd760f6e630f38df320c7c318235c8500b0545abbc5",
          "sha256": "d4f8f37ae3f0d11d5a0103b989ae916e52b8b114cf46da4d37c5b8f87c59c1a5",
          "sha1": "d35a0bd69f3734e9e2f13ff06a87bba4bc07bb64",
          "md5": "35986f81970bc1cdaa4fd9b8bf5146c9"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-1.0-sources.jar",
          "url": "jni_release-1.0-sources.jar",
          "size": 5459,
          "sha512": "61c8d0b11708383673e2d967abe5948df4f9f1c20f77852bfc8e4da61a83bb5c2e7561a02692dc183a64b4f842555d66ebd142d02b6295313fcda91f9e8e0c15",
          "sha256": "0762cdfe1e25701b53f0e55fde69135e74f25328f4b1c60e4778701833bfab6e",
          "sha1": "09a60f323f1b590e7921cd33327514fe4d916cb1",
          "md5": "3cf8aa129d418b4388b02cea9ff9819b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "jni_release-1.0-javadoc.jar",
          "url": "jni_release-1.0-javadoc.jar",
          "size": 283170,
          "sha512": "f1cd60b5c089dd10d7f4c88bf42cda96a6e88ded43288cb41d482b7ab73e0f5caec452a1482baacafca5fe3212a85b4606e7d3965bffd7ea359775a08ebbfa29",
          "sha256": "b4f8c74098a5450905d6769260b8bb51dda97e39d2618563230ba055c23c7b1c",
          "sha1": "7a8987b67b367f2141847175c5db8a8eef7609da",
          "md5": "006ccd3377cf4ae1812821a8b166a739"
        }
      ]
    }
  ]
}
