{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.3.aar",
          "url": "android_release-0.1.3.aar",
          "size": 1142003,
          "sha512": "1db36ee30d5ff45b782433ddcd0334df614a75cba16fc645da7e02db96a1edf353e685028e0b52bb592c6ba376a8296f304b260915bdb4383c945e4f62449003",
          "sha256": "354101b8c22f856eb54baf22057e1c1016d949c1f2bd189e63f3c809c5cc3421",
          "sha1": "03a4565b65af3399ff0d8bbd484b7d550f1a1444",
          "md5": "10cdc7098276ed4f3fb41e55267619aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.3"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.3.aar",
          "url": "android_release-0.1.3.aar",
          "size": 1142003,
          "sha512": "1db36ee30d5ff45b782433ddcd0334df614a75cba16fc645da7e02db96a1edf353e685028e0b52bb592c6ba376a8296f304b260915bdb4383c945e4f62449003",
          "sha256": "354101b8c22f856eb54baf22057e1c1016d949c1f2bd189e63f3c809c5cc3421",
          "sha1": "03a4565b65af3399ff0d8bbd484b7d550f1a1444",
          "md5": "10cdc7098276ed4f3fb41e55267619aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.3-sources.jar",
          "url": "android_release-0.1.3-sources.jar",
          "size": 286489,
          "sha512": "e35db8439596494508e65aefef3e566536df092617ed12d05654c1f89f53535ba7e3f01f3b3ec3ceb8f1810cc6aff8cb940230ad8b7b16071acc88db2c37e101",
          "sha256": "d5302e068b7fb24d5bb174d863243e3681cdcbdb4f04b565be9d70db06532a06",
          "sha1": "d216d283a30e618ef72e4f4067b5e972408882be",
          "md5": "695523b908c6ff968330c321a2dcc069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.3-javadoc.jar",
          "url": "android_release-0.1.3-javadoc.jar",
          "size": 2026930,
          "sha512": "8dd8d950b3b84da2f1afadf2acf6acfddc7fda61d674302e33260b38691b4e3a2d5497b38732850c1510ffd2123c502e055dde64c9b95ce4904dc266526b491e",
          "sha256": "16e5f12af64e170787abf4b8640c612c1f45f91b07c5cf1ac5edf2de1df8874a",
          "sha1": "14089735f86513df8f3d46f4c3ccb714111aee1e",
          "md5": "67b9a6a805b5a390fefd2c9b2534ac6f"
        }
      ]
    }
  ]
}