{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.device_info",
    "module": "device_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 7481,
          "sha512": "a38370448e4874ee5fe251ec49dc190f5dee15c378e146cbd5e3cf4804dde116d10122cc6d98788389c0d2e9f038eed3e44303e136d33a82806c98b232cb98c4",
          "sha256": "813f5e4e22cdb7bd9ff3d1c3fc5bdd78319cf0104119223756aef494c9e67b86",
          "sha1": "282262ea8d8e14cc931f87cca70f129da4a6dd8a",
          "md5": "8e265e1b4166370b6ea72c16f0bd73e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        }
      ],
      "files": [
        {
          "name": "device_info_plus_release-1.0.aar",
          "url": "device_info_plus_release-1.0.aar",
          "size": 7481,
          "sha512": "a38370448e4874ee5fe251ec49dc190f5dee15c378e146cbd5e3cf4804dde116d10122cc6d98788389c0d2e9f038eed3e44303e136d33a82806c98b232cb98c4",
          "sha256": "813f5e4e22cdb7bd9ff3d1c3fc5bdd78319cf0104119223756aef494c9e67b86",
          "sha1": "282262ea8d8e14cc931f87cca70f129da4a6dd8a",
          "md5": "8e265e1b4166370b6ea72c16f0bd73e3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-1.0-sources.jar",
          "url": "device_info_plus_release-1.0-sources.jar",
          "size": 3125,
          "sha512": "b9cb00c45bc93bb579209e570cc6bccd93db4bc096aa171224af075e8692c8781fa658075ca0fac74487a49fa688512631128c1179a925ebcfc7e0df2ac1c49f",
          "sha256": "881c3ff7cebe7fa7dcbc12c9cd124932bc1986640af6e78c69608b8c0a68b939",
          "sha1": "baedb19f71c1d446920d5e7702e29ce5e368c7d4",
          "md5": "cd8cd56bd2b0956e8e0eb8238a55e8dc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "device_info_plus_release-1.0-javadoc.jar",
          "url": "device_info_plus_release-1.0-javadoc.jar",
          "size": 260821,
          "sha512": "a5fcc98e2415bbe94a3a575161a7d863446d3163420ec9b0e78f5bc8ba8e43a64bfe971d39bc451dd40312a4b3ae090aeeb10e965fa9bebaa93c7fddcfa4d1c9",
          "sha256": "a7519e8acc2a0b46026729fc02b345d832d2d9280c79e7861ff74471052b9da7",
          "sha1": "4e036ffc349db7e5e960d775ba302d5160dea23e",
          "md5": "31673292b78fc54e977caf9251f6571b"
        }
      ]
    }
  ]
}
