{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.34-test.343",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.34-test.343"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.34-test.343.aar",
          "url": "android_release-0.1.34-test.343.aar",
          "size": 1440796,
          "sha512": "4975fc320661e2b59b6d57f168f2b9fb1cd0f6f60964533dceb33f6c6e14f7e1ad9530688c4c237bff4480057e979373a57e9854a8653f88721fe149d365f0b1",
          "sha256": "b350c47707abfbbf3ad509d76d5f96af7cf41893cdf07b0e2f0577aa17d96690",
          "sha1": "b9863e962990f396d63e6b2c229c60ded45df741",
          "md5": "3c773efa3babb7e88e4ddcdd0d622c3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.34-test.343"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.34-test.343.aar",
          "url": "android_release-0.1.34-test.343.aar",
          "size": 1440796,
          "sha512": "4975fc320661e2b59b6d57f168f2b9fb1cd0f6f60964533dceb33f6c6e14f7e1ad9530688c4c237bff4480057e979373a57e9854a8653f88721fe149d365f0b1",
          "sha256": "b350c47707abfbbf3ad509d76d5f96af7cf41893cdf07b0e2f0577aa17d96690",
          "sha1": "b9863e962990f396d63e6b2c229c60ded45df741",
          "md5": "3c773efa3babb7e88e4ddcdd0d622c3b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.34-test.343-sources.jar",
          "url": "android_release-0.1.34-test.343-sources.jar",
          "size": 370859,
          "sha512": "8f57afb84dc539ab0f0fc461c9fddbe7738900318aec943aab9c1de181f7a67fb69c07a79816fe0dd95a91854a3978f5278bfd4c29a335d30d07d302f122ccf9",
          "sha256": "5c17907f71777321481c725d3c99d100b61b8819aedf3db07bb84e1afb494927",
          "sha1": "6fdac062133807c5abf2f1bce1091e192a11f503",
          "md5": "0ee26b00ab6c0f4c805004d651c6b7b8"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.34-test.343-javadoc.jar",
          "url": "android_release-0.1.34-test.343-javadoc.jar",
          "size": 2414709,
          "sha512": "53784c493724a5092d8b4ba41456323eaaddcbc3de1ff028584df3ddad09d3e8358cc4c1c248f55c49c8d548d389b8eee8dca0150aeb16a2b7c4b74c331d2d8b",
          "sha256": "88da19d4a4bb8f0d5c1f209945c0f2f3456dbeeeeecbebe139a3dda0d4269f74",
          "sha1": "30f690e13493579ef33fd447de0210d82e323e56",
          "md5": "3328559ca9c15e878cdfa99a9f86b5d0"
        }
      ]
    }
  ]
}