{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-1.0.aar",
          "url": "android_release-1.0.aar",
          "size": 1199480,
          "sha512": "116da21a329888f3e68382a8d526e20f2fc33e25fabf7be3cf266d1f3a3661aa30cd5b6db0d68c5e4c23ba4aff7759abfc9b322e361f99dba3fb158e0abedfdb",
          "sha256": "8f8bba639442406742843e87d157303ce42edc1f0f5bcb7b1916d8c99f5b9264",
          "sha1": "f2fe0048f5ed2c395ed9632fcf3877f59272031d",
          "md5": "822b8c499e73a409a123e54e3ec536eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-1.0.aar",
          "url": "android_release-1.0.aar",
          "size": 1199480,
          "sha512": "116da21a329888f3e68382a8d526e20f2fc33e25fabf7be3cf266d1f3a3661aa30cd5b6db0d68c5e4c23ba4aff7759abfc9b322e361f99dba3fb158e0abedfdb",
          "sha256": "8f8bba639442406742843e87d157303ce42edc1f0f5bcb7b1916d8c99f5b9264",
          "sha1": "f2fe0048f5ed2c395ed9632fcf3877f59272031d",
          "md5": "822b8c499e73a409a123e54e3ec536eb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-1.0-sources.jar",
          "url": "android_release-1.0-sources.jar",
          "size": 308984,
          "sha512": "5e96f0bde38bbccc7fdf005c18c49e0ed084785ed1666fe8f304d17d5be0a96f1b69781af972a9f9a12b275f9243982322900f02e7f331e1d98df49ebd85b2e2",
          "sha256": "788936a4b472ca589d3dd340a304097f3082c2d0e7598f3b0cb92d6df8ae257e",
          "sha1": "d1800c03295c65af8405ca13d87807eae79a7107",
          "md5": "25497272c670fe3a2c3700a02ec2e677"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-1.0-javadoc.jar",
          "url": "android_release-1.0-javadoc.jar",
          "size": 2100249,
          "sha512": "7896d9c30773d0773e72a3e30ce5244279755056b7dba794a5f73b6041aae818f42f4dfb4ac3fb4d58f71570e9162d45144330a45209fd888f7063c06099da5e",
          "sha256": "a3033b1773f8e6955f9da01dfadaf10deadd3aca3e9e4be93361802243ddcb86",
          "sha1": "bbd4e6d346f10e7a52a975f3015437479d1722d7",
          "md5": "cab2aa7fc92d53e704548d8e3528fc47"
        }
      ]
    }
  ]
}
