{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-1.0.aar",
          "url": "android_release-1.0.aar",
          "size": 1142003,
          "sha512": "1db36ee30d5ff45b782433ddcd0334df614a75cba16fc645da7e02db96a1edf353e685028e0b52bb592c6ba376a8296f304b260915bdb4383c945e4f62449003",
          "sha256": "354101b8c22f856eb54baf22057e1c1016d949c1f2bd189e63f3c809c5cc3421",
          "sha1": "03a4565b65af3399ff0d8bbd484b7d550f1a1444",
          "md5": "10cdc7098276ed4f3fb41e55267619aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-1.0.aar",
          "url": "android_release-1.0.aar",
          "size": 1142003,
          "sha512": "1db36ee30d5ff45b782433ddcd0334df614a75cba16fc645da7e02db96a1edf353e685028e0b52bb592c6ba376a8296f304b260915bdb4383c945e4f62449003",
          "sha256": "354101b8c22f856eb54baf22057e1c1016d949c1f2bd189e63f3c809c5cc3421",
          "sha1": "03a4565b65af3399ff0d8bbd484b7d550f1a1444",
          "md5": "10cdc7098276ed4f3fb41e55267619aa"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-1.0-sources.jar",
          "url": "android_release-1.0-sources.jar",
          "size": 286489,
          "sha512": "e35db8439596494508e65aefef3e566536df092617ed12d05654c1f89f53535ba7e3f01f3b3ec3ceb8f1810cc6aff8cb940230ad8b7b16071acc88db2c37e101",
          "sha256": "d5302e068b7fb24d5bb174d863243e3681cdcbdb4f04b565be9d70db06532a06",
          "sha1": "d216d283a30e618ef72e4f4067b5e972408882be",
          "md5": "695523b908c6ff968330c321a2dcc069"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-1.0-javadoc.jar",
          "url": "android_release-1.0-javadoc.jar",
          "size": 2026714,
          "sha512": "7a17eae91efc3b7b1077f67afd490164d1217e07a9090d940bb2ebf616dd6ddb4a7b908a09956daf649be62b26daa52547928fb57a16464a17fe37857359942e",
          "sha256": "282fcc569f8b6db5f8591f5ec852671741faee876b168d5c9ac846286393f5e3",
          "sha1": "4f66b7ace888fb7087ee706eebe66ac3bbc8d120",
          "md5": "3b6d2f76de56d61f9e5d180a74613504"
        }
      ]
    }
  ]
}
