{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.24-test.291",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.24-test.291"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.24-test.291.aar",
          "url": "android_release-0.1.24-test.291.aar",
          "size": 1351343,
          "sha512": "3a0856b7515d5916b46e3add6bc76e71df22d27154089f2a7fc0e7c24b3cc5ab3e19c2f24a26284aff7e49b1f9e59f811522c9aec8dd12ac04053ffe0ad8f717",
          "sha256": "15e2a813f091d1be3371d8892174d941b1c686164c9acc76acdb7539f530eb13",
          "sha1": "ab7c66488bf1834fdf9d672b1fab6eec43402406",
          "md5": "95e54c2b33a7ec07fa87bb82ee8154b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.24-test.291"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.24-test.291.aar",
          "url": "android_release-0.1.24-test.291.aar",
          "size": 1351343,
          "sha512": "3a0856b7515d5916b46e3add6bc76e71df22d27154089f2a7fc0e7c24b3cc5ab3e19c2f24a26284aff7e49b1f9e59f811522c9aec8dd12ac04053ffe0ad8f717",
          "sha256": "15e2a813f091d1be3371d8892174d941b1c686164c9acc76acdb7539f530eb13",
          "sha1": "ab7c66488bf1834fdf9d672b1fab6eec43402406",
          "md5": "95e54c2b33a7ec07fa87bb82ee8154b5"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.24-test.291-sources.jar",
          "url": "android_release-0.1.24-test.291-sources.jar",
          "size": 341147,
          "sha512": "0de0180df5e140f992807740d2506ece667d8d37b8e6e2fdb6e61466a94cc41f8d8d4a3008562750539a26738f5a60624d6adb4139f778e05be77aed3925f7ff",
          "sha256": "0cb5bde233c635337a71b84151569f22076f4d9c453b87d7a301a14eecd15407",
          "sha1": "51e70afaabfd70a8a29434809702592e311a0d2c",
          "md5": "49b6fa7d2cabb2325f278e5732b25bff"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.24-test.291-javadoc.jar",
          "url": "android_release-0.1.24-test.291-javadoc.jar",
          "size": 2335064,
          "sha512": "ecaa702112507ac14481c95df9aeea66c23fe8d850e8dd2621c8a590a12739b513bbf7f9c787c0b41ae2d3b88614da1a5ddb7b470b416428ecc67b7116964803",
          "sha256": "b993df17ddaea55433682e3c861f570f1027722565701515dd0ea3bdae901060",
          "sha1": "8acce3e3744f205c3598fb40c7c1144778b87c3d",
          "md5": "f5add9b0dd3f70b1b5bc03dde769c219"
        }
      ]
    }
  ]
}