{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mapbox.maps.mapbox_maps",
    "module": "mapbox_maps_flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0.aar",
          "url": "mapbox_maps_flutter_release-1.0.aar",
          "size": 1100824,
          "sha512": "c69039aac974f663f076ecb3012f72b5777887c96095ff878e9ea1ea57120186ff5d32d60274b46c592f8b3804fe40a1f6cd639e2cf55b2994cad145dff2456c",
          "sha256": "b2b8108647408e08bf9e5ed3716cf9695b5b0712f11f72ad3d9e1596985a0053",
          "sha1": "47889cc85eb28707db18e62e36584091c5d71e42",
          "md5": "87cefa7d7e812fcf991dc75725fecdb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android-ndk27",
          "version": {
            "requires": "11.19.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0.aar",
          "url": "mapbox_maps_flutter_release-1.0.aar",
          "size": 1100824,
          "sha512": "c69039aac974f663f076ecb3012f72b5777887c96095ff878e9ea1ea57120186ff5d32d60274b46c592f8b3804fe40a1f6cd639e2cf55b2994cad145dff2456c",
          "sha256": "b2b8108647408e08bf9e5ed3716cf9695b5b0712f11f72ad3d9e1596985a0053",
          "sha1": "47889cc85eb28707db18e62e36584091c5d71e42",
          "md5": "87cefa7d7e812fcf991dc75725fecdb2"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0-sources.jar",
          "url": "mapbox_maps_flutter_release-1.0-sources.jar",
          "size": 162297,
          "sha512": "0d627a84b3b247e14ee8b62f13fa0c96453700b4d208f2d43d77feb682af5d0a0e6ba2c03d70fd7f27f740105c2c02d4c7864c22a843ad81cbbe79577a0e1aae",
          "sha256": "14b5e0114c386ae398179c0540167ef7e6f958976ca8e894946feeb557c4bd7e",
          "sha1": "d900c0b065052ca46c6bda4f4f7b34aaf0d456a2",
          "md5": "93bcdd2bb45ee374e32154361e43a9e1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0-javadoc.jar",
          "url": "mapbox_maps_flutter_release-1.0-javadoc.jar",
          "size": 2082765,
          "sha512": "be35d99282257a7f48799f9f6c3ff99b95ab71e8f3f283eeca3affc78b0efca926fe69143020157a646fe7e50546410f8c612e732fb525a9d2146d864da01c95",
          "sha256": "8513a99744c0cdaa25499355dee8f6858eb1bc08be0a35a1578c623921d943d8",
          "sha1": "59cf00d3354afd9f34071016e4af05b63a3d038d",
          "md5": "c903515bf632f3f8cc1f1cf391eaeadc"
        }
      ]
    }
  ]
}
