{
  "formatVersion": "1.1",
  "component": {
    "group": "com.mapbox.maps.mapbox_maps",
    "module": "mapbox_maps_flutter_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0.aar",
          "url": "mapbox_maps_flutter_release-1.0.aar",
          "size": 1108730,
          "sha512": "f06aa7fc307ecdef1e7eecd76213bba69abd04ff6190f3bd70500cf862dd86b7e80a9b1b12c3bb78b9bad3e6e41de0662a24a9b96418287cc6793b72b1e6937a",
          "sha256": "cea248c5f2ec4e92652332753dc84f58cbafc3fd63f6ab893d6dc467608fa49e",
          "sha1": "057ccc6a43391ff1ecea6b83ca37867219651f74",
          "md5": "aa423ea7a20e8783a1c4153d9718207a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "com.mapbox.maps",
          "module": "android-ndk27",
          "version": {
            "requires": "11.22.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.5.0"
          }
        },
        {
          "group": "androidx.lifecycle",
          "module": "lifecycle-runtime-ktx",
          "version": {
            "requires": "2.6.2"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0.aar",
          "url": "mapbox_maps_flutter_release-1.0.aar",
          "size": 1108730,
          "sha512": "f06aa7fc307ecdef1e7eecd76213bba69abd04ff6190f3bd70500cf862dd86b7e80a9b1b12c3bb78b9bad3e6e41de0662a24a9b96418287cc6793b72b1e6937a",
          "sha256": "cea248c5f2ec4e92652332753dc84f58cbafc3fd63f6ab893d6dc467608fa49e",
          "sha1": "057ccc6a43391ff1ecea6b83ca37867219651f74",
          "md5": "aa423ea7a20e8783a1c4153d9718207a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0-sources.jar",
          "url": "mapbox_maps_flutter_release-1.0-sources.jar",
          "size": 163983,
          "sha512": "c69044e35555763460021eb6c202c25f88f38e1cc4258278a53f797ef090c3c8c590bd62a9dca97ecde80afaa41279e1917455c65fe8c0508e7efb9f5da0f3f6",
          "sha256": "5fae0f575cf7d51cc56b0c7cc69893f72725d23ff246092ecef3a7b4fc5132e0",
          "sha1": "d244501cee736d53e42f1a22f41a4703a2e5f1a2",
          "md5": "5ded8b5d0341eb382ba9b113bef7bc85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "mapbox_maps_flutter_release-1.0-javadoc.jar",
          "url": "mapbox_maps_flutter_release-1.0-javadoc.jar",
          "size": 2101481,
          "sha512": "5b776b41fb7bdace7c4c70dfa738e5d0d695996f8bf34f8adca27ac56225dee89aa2dbe0a30e312d527845c01651488f8e678560c3b96eab95afa82370999300",
          "sha256": "7e9535ec9b7bafe8f9b81bc91cfd65bfc20faecddfde6cba85232ef9d4b39447",
          "sha1": "0fdcdf4c933d72064f092a5327aa46322fd557cc",
          "md5": "8e04c5737fcd02c6b326c5ce8aa09224"
        }
      ]
    }
  ]
}
