{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.14",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.14.aar",
          "url": "android_release-0.1.14.aar",
          "size": 1137694,
          "sha512": "2f59b8ab9c333b27b0b8b3466dbc8823165b8aa8214162beba5b499a94e8b3a18e4f422906443a8ce1c54dfe112e30dac486b2f4ae456311942b5c8557c19ac9",
          "sha256": "ff6901343646b85c1f06805f3787459bd1903e447f7ce65832de7e7127937cc1",
          "sha1": "a057deafe201b60d04a463ce3ce01a93d6fe59f6",
          "md5": "e9ebda53a7ca20b4cb83ddcc6eccd1af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.14"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.14.aar",
          "url": "android_release-0.1.14.aar",
          "size": 1137694,
          "sha512": "2f59b8ab9c333b27b0b8b3466dbc8823165b8aa8214162beba5b499a94e8b3a18e4f422906443a8ce1c54dfe112e30dac486b2f4ae456311942b5c8557c19ac9",
          "sha256": "ff6901343646b85c1f06805f3787459bd1903e447f7ce65832de7e7127937cc1",
          "sha1": "a057deafe201b60d04a463ce3ce01a93d6fe59f6",
          "md5": "e9ebda53a7ca20b4cb83ddcc6eccd1af"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.14-sources.jar",
          "url": "android_release-0.1.14-sources.jar",
          "size": 284971,
          "sha512": "c30aa848974f339495e2e108dc3979a8d4abd81466e5d10b10a138a30989cd06d38290ff840050cb7d2d9abfef8ccb06c85bf04a47c0fadbf47cac2ac8747fcd",
          "sha256": "762105942f03c0e0cdb01839b52085dd3389fccab26ad28ec395e499deae5e3c",
          "sha1": "80832932b4a0da0bf38603f02ab7c6e41d808ff1",
          "md5": "44356fa04d0bd902463b7cf8134dc914"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.14-javadoc.jar",
          "url": "android_release-0.1.14-javadoc.jar",
          "size": 2026085,
          "sha512": "c91289139708c36d20eecdeaef11e66a83ebdd271f40e37ded08b7ef7b427a3508855bd97942cf33a4446927f37bb794c2ae7c1d09124696819596d9e51c14c3",
          "sha256": "752082a120e63eb76d45e3a00b44235ee5180971902d26166ab0dc933ca26c41",
          "sha1": "c1add0bfb2149fe9a8344f73ab89be7fed702692",
          "md5": "3929485e7d9bd4f4b4a74d1c9fdb7567"
        }
      ]
    }
  ]
}