{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 70039,
          "sha512": "921c44829e6661907207508ace7449ff11eb504aa7f8327de8c9b27745ef5bb579ecd398080aefe94389e4d11daeec27be693a49d4f1b056cf0418710d877031",
          "sha256": "32785b98045c733b3342d69cf93018d1ffb1a0da0b04047aa90be4542ebe9612",
          "sha1": "8666d8a398e9c6b435a5842bae91d42b278f00a6",
          "md5": "c01f5ec6acbc6e1723b2c7b33a50f68a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 70039,
          "sha512": "921c44829e6661907207508ace7449ff11eb504aa7f8327de8c9b27745ef5bb579ecd398080aefe94389e4d11daeec27be693a49d4f1b056cf0418710d877031",
          "sha256": "32785b98045c733b3342d69cf93018d1ffb1a0da0b04047aa90be4542ebe9612",
          "sha1": "8666d8a398e9c6b435a5842bae91d42b278f00a6",
          "md5": "c01f5ec6acbc6e1723b2c7b33a50f68a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-sources.jar",
          "url": "image_picker_android_release-1.0-sources.jar",
          "size": 26588,
          "sha512": "964e4ee3747874d7ec0e6046ff5186e6238290e41f3e5aecfd1c7e87c3b2143f57ce7bb64b8b3235c02f6876ef5c8e99874050bfc1c9d2c364988b1deb02d450",
          "sha256": "0dc986023c445e827cf3fff727d4540ca879f699cf07e7caa593d9f30210b40b",
          "sha1": "bd666d009c2d083a00755525ae8e92c3adc13ff4",
          "md5": "c36bb10dbbc7e6ce6c008b12cee85273"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-javadoc.jar",
          "url": "image_picker_android_release-1.0-javadoc.jar",
          "size": 382978,
          "sha512": "7c0169fd1844712f2c7884638643d26527a0d1c147ed6942009518e020bd86bac4e9fc81c756077d619d61ae2ab94534c53a645f52d4c148b965d031ead965d1",
          "sha256": "190abcd7d8828e35dbcac331dbf7a4e7008547aaaca77fb85bbfb0f4a0e88bf8",
          "sha1": "e4dc9e6f208422e746b577598f3cdd3df9b60cea",
          "md5": "6d6161f0bdb35788fddcc43e0b94a8bd"
        }
      ]
    }
  ]
}
