{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.imagepicker",
    "module": "image_picker_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 83942,
          "sha512": "f0eb6b760b7820e118e50b30c2b1d78f10869778af160108aa036d8b8cfb5fed9393ae6003f4f6d25f696ed0913cf9b2c465605eb9dad99dba218cef5a396da8",
          "sha256": "1eb42d2b5cee3c8ad0fcfbb1421358be0d20787a21c9a5b714bc5fdca2f16e9b",
          "sha1": "75100bfc4af30ef7fd6fec555fc509c4a3dc4b30",
          "md5": "39eabec51128b4c3f923ab663483be0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.18.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        },
        {
          "group": "androidx.exifinterface",
          "module": "exifinterface",
          "version": {
            "requires": "1.4.2"
          }
        },
        {
          "group": "androidx.activity",
          "module": "activity",
          "version": {
            "requires": "1.12.4"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "image_picker_android_release-1.0.aar",
          "url": "image_picker_android_release-1.0.aar",
          "size": 83942,
          "sha512": "f0eb6b760b7820e118e50b30c2b1d78f10869778af160108aa036d8b8cfb5fed9393ae6003f4f6d25f696ed0913cf9b2c465605eb9dad99dba218cef5a396da8",
          "sha256": "1eb42d2b5cee3c8ad0fcfbb1421358be0d20787a21c9a5b714bc5fdca2f16e9b",
          "sha1": "75100bfc4af30ef7fd6fec555fc509c4a3dc4b30",
          "md5": "39eabec51128b4c3f923ab663483be0f"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-sources.jar",
          "url": "image_picker_android_release-1.0-sources.jar",
          "size": 26339,
          "sha512": "6b66bb404855e49fae2b7d7ef302441e16bb4dd17b214f2ed8fa2489c03651bf0ab1358ae3093fded6ffb62e4f53d2671ee1c6b4b6cf23d23ff6bcd0b39bfc42",
          "sha256": "7d37f0934a45706374461cf175bb5391dd5fee6d6c91eee258c987e926ff7fc9",
          "sha1": "f58f87734345f34aeebf11488442a1144706311b",
          "md5": "0f6c19b98d7c74c7d21582cd6130d698"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_picker_android_release-1.0-javadoc.jar",
          "url": "image_picker_android_release-1.0-javadoc.jar",
          "size": 385265,
          "sha512": "5fe591e31bc1f282d96855df9cb0249aa94ef08099dbec9212760f024fb79d4d227120526664065ffb16f3bee693fb59d9619f7f6fae7258b7306b076f6ccb20",
          "sha256": "820141ec49abe93c8e1b27199143d85c4d061473e78aefb3bd1dfb996f5d8828",
          "sha1": "b5bf8cabf81121ccbfb1619889b5858cd3dc5322",
          "md5": "4cffe4667db69e9c8a5da18c704d2dbb"
        }
      ]
    }
  ]
}
