{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.19-test.302",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.19-test.302"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.19-test.302.aar",
          "url": "android_release-0.1.19-test.302.aar",
          "size": 1353829,
          "sha512": "fc1c187b5c8a281ace597738744a44fd07998c6e32183da912a4eb51dfe39d0913dfdc554242aaf015de34e125cbb1d31c88a996f969c72b76c1264111b66fcc",
          "sha256": "1abe251e3a63a99ce91165a63ae2f45e7e504b9337e47b9d2d782fc4f1c55279",
          "sha1": "7bc4bb06afcb53e6a80f6b54634400b4ac28b037",
          "md5": "b77cee0a18844ce365499d573bab3588"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.19-test.302"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.19-test.302.aar",
          "url": "android_release-0.1.19-test.302.aar",
          "size": 1353829,
          "sha512": "fc1c187b5c8a281ace597738744a44fd07998c6e32183da912a4eb51dfe39d0913dfdc554242aaf015de34e125cbb1d31c88a996f969c72b76c1264111b66fcc",
          "sha256": "1abe251e3a63a99ce91165a63ae2f45e7e504b9337e47b9d2d782fc4f1c55279",
          "sha1": "7bc4bb06afcb53e6a80f6b54634400b4ac28b037",
          "md5": "b77cee0a18844ce365499d573bab3588"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.19-test.302-sources.jar",
          "url": "android_release-0.1.19-test.302-sources.jar",
          "size": 342579,
          "sha512": "ae738705cdcf242ade84e85607f69a39588810145d93476aa4ef23d7300b7123681f7f0f81fccb1cfad8ac15c69c66d75885df0603a92041226d789ed6633823",
          "sha256": "ad30f266a65e8f9019250858480604d32b563333d812efffd663c6969b239f44",
          "sha1": "f2f55f5721494163e0ea78be9399a5c01b82b79e",
          "md5": "20a798a471375a1eca26e928e889bdf3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.19-test.302-javadoc.jar",
          "url": "android_release-0.1.19-test.302-javadoc.jar",
          "size": 2343332,
          "sha512": "75dbce8e38f6d06aebe296ad6f50a0bd4bd1c77f0bae5f330d6d4c09b2d80eef84895c1d42331f56652e9871ab4cfd7467a4aadfe291528d3a23d6a0bb2e0b5b",
          "sha256": "7964a8e9558b016e63e2a8df0033f6b8970a9d07bb9a824e283154e13554b341",
          "sha1": "6d43bf1d88d48e86bef46a56ddd91179845b4532",
          "md5": "c9f11f34fc613bcccb99ed7d7985d9a2"
        }
      ]
    }
  ]
}