{
  "formatVersion": "1.1",
  "component": {
    "group": "com.dexterous.flutterlocalnotifications",
    "module": "flutter_local_notifications_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-1.0.aar",
          "url": "flutter_local_notifications_release-1.0.aar",
          "size": 82706,
          "sha512": "f0676cc7795a39878ab0cdc20d1f2410f60b42c021f55677f2b1101fd01b2ad7e7ecc20dc97d3f77084470f243e782adb40c76229f410ef7c7620a04a81e39a8",
          "sha256": "37f4ccf7b0d1437b29d8d4868cd26c5898f519df2437911ceaa557975a259783",
          "sha1": "ab92cb83901c4632116960b93e8afdbe95941698",
          "md5": "89615829d2979a4fcd2477f22b926169"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.3.0"
          }
        },
        {
          "group": "androidx.media",
          "module": "media",
          "version": {
            "requires": "1.1.0"
          }
        },
        {
          "group": "com.google.code.gson",
          "module": "gson",
          "version": {
            "requires": "2.12.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_local_notifications_release-1.0.aar",
          "url": "flutter_local_notifications_release-1.0.aar",
          "size": 82706,
          "sha512": "f0676cc7795a39878ab0cdc20d1f2410f60b42c021f55677f2b1101fd01b2ad7e7ecc20dc97d3f77084470f243e782adb40c76229f410ef7c7620a04a81e39a8",
          "sha256": "37f4ccf7b0d1437b29d8d4868cd26c5898f519df2437911ceaa557975a259783",
          "sha1": "ab92cb83901c4632116960b93e8afdbe95941698",
          "md5": "89615829d2979a4fcd2477f22b926169"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_release-1.0-sources.jar",
          "url": "flutter_local_notifications_release-1.0-sources.jar",
          "size": 44296,
          "sha512": "28c95b353ca7690e871fb34887ebcb046f1b7b79c21dc5ef2e2d47829c3df032d18383542ba5326e9becd9df058fa3f7ebc06a4663b9063dc1d80d438303d229",
          "sha256": "4050f37d184adb6bca49329a2ef070696dd09d95dc355d23d3c8f5211599368e",
          "sha1": "f77ee9d270f9c83037fefc69016249aee0925191",
          "md5": "f34f6b812fea4ac6d3020162c8f6345d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_local_notifications_release-1.0-javadoc.jar",
          "url": "flutter_local_notifications_release-1.0-javadoc.jar",
          "size": 417732,
          "sha512": "35edb61f42cfce3f6656597de61abf435bc16463bddbb6081f2490d79fed79e6facb31425cbfeb183fff8bd1e9ade388b4979ed26578d8ebe7bbb53e4aaceba0",
          "sha256": "068d840f950a01c1dc19380ac8921c55322911001bbfab1951707fc3808b72fb",
          "sha1": "6a1cbcac9e30c0341e17c817833d245f1f745f70",
          "md5": "1abbceec99538fb782cd4901f396ffb7"
        }
      ]
    }
  ]
}
