{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.23-test.326",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.23-test.326"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.23-test.326.aar",
          "url": "android_release-0.1.23-test.326.aar",
          "size": 1359090,
          "sha512": "26eace65b3aa4dfd323ee0a2d34975050228f61aa2baa2ec0abcacb918d12eff3b681fc0770b139e728681037d0f6826af78c9689b1d7ab3e789d9fac56fe97d",
          "sha256": "86e4b29dace1caac6cacdee39e657ce20614d8d029a44cddfa7c52d92138a34e",
          "sha1": "ea2d356a3869476f1d9ebbb1334d7b3abeb4b132",
          "md5": "a3fe117c035e88f3ef228754e236a749"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.23-test.326"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.23-test.326.aar",
          "url": "android_release-0.1.23-test.326.aar",
          "size": 1359090,
          "sha512": "26eace65b3aa4dfd323ee0a2d34975050228f61aa2baa2ec0abcacb918d12eff3b681fc0770b139e728681037d0f6826af78c9689b1d7ab3e789d9fac56fe97d",
          "sha256": "86e4b29dace1caac6cacdee39e657ce20614d8d029a44cddfa7c52d92138a34e",
          "sha1": "ea2d356a3869476f1d9ebbb1334d7b3abeb4b132",
          "md5": "a3fe117c035e88f3ef228754e236a749"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.23-test.326-sources.jar",
          "url": "android_release-0.1.23-test.326-sources.jar",
          "size": 346097,
          "sha512": "6ed5aac6debfed9b8136e642f19e96887d5ea6818e26fc0cb1ffbce3b50b2cd013efb52c0b2a1d7a76951fd6a6cbb1e11931f73c316263f7485a508318bb7f1c",
          "sha256": "4e3a429fc573679d2e77192161c1cebe48e570f0b6a510f5405576d6983267c6",
          "sha1": "4d0293ae92ebcfd7fcaa62bc7afa940d64fc0997",
          "md5": "cd70b4f649cd04a6b6c049d49fef139a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.23-test.326-javadoc.jar",
          "url": "android_release-0.1.23-test.326-javadoc.jar",
          "size": 2368398,
          "sha512": "9cc3d9c8ba19e39bfdc51af869ba6695fef53273aace789944b32c9c20fbe90b1b873c6d39e94066e683e9b7a876497cdcd4346a4e08be1c02ce2269bbc96d49",
          "sha256": "ccfaca7e7f2a504db4c70fe4a9fed1b3d02163d0f19a655c75cebd27f144deb6",
          "sha1": "3cab24a1cc6b3f7e46f4e9b3541b5b408a55478c",
          "md5": "388d238f8eef0d96161509ac3bcf86f6"
        }
      ]
    }
  ]
}