{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.13-test.295",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.13-test.295"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.13-test.295.aar",
          "url": "android_release-0.1.13-test.295.aar",
          "size": 1353018,
          "sha512": "9ae3df5875ada6ce3914bc302fc2e2f988afef5b421f280ae834b0d67e0589fb07013119ac77425645ecb3164032e2ab266896c6ea14a8acdbd8f85144a96f81",
          "sha256": "b5332ef55c9caa933c94ca4c4ae4850f34561411bfb1e4207a016b2204bc4985",
          "sha1": "dbfe6629494a86276c4915a6626926317652c695",
          "md5": "9e6c6ebf9f1b3860fe4f8fa1ac8f3362"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.13-test.295"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.13-test.295.aar",
          "url": "android_release-0.1.13-test.295.aar",
          "size": 1353018,
          "sha512": "9ae3df5875ada6ce3914bc302fc2e2f988afef5b421f280ae834b0d67e0589fb07013119ac77425645ecb3164032e2ab266896c6ea14a8acdbd8f85144a96f81",
          "sha256": "b5332ef55c9caa933c94ca4c4ae4850f34561411bfb1e4207a016b2204bc4985",
          "sha1": "dbfe6629494a86276c4915a6626926317652c695",
          "md5": "9e6c6ebf9f1b3860fe4f8fa1ac8f3362"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.13-test.295-sources.jar",
          "url": "android_release-0.1.13-test.295-sources.jar",
          "size": 341874,
          "sha512": "c5a806ed4e742c48e85bc23030c4d0c4b4bc32167e481ffbdaf904e6726667322f987dd4eb6075173a1f7e4bd3e30770ce5f97b96a83d922588a5066fffaeb37",
          "sha256": "c56fd0225f3445b3deac60c5e8bef1fcf859a044271083afd0b5a4b5ca499769",
          "sha1": "560d632baf97e8506ff8a7297c4193c2119be6e3",
          "md5": "12e349d74d39bf83f4374401adf3a858"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.13-test.295-javadoc.jar",
          "url": "android_release-0.1.13-test.295-javadoc.jar",
          "size": 2339607,
          "sha512": "d8474a64db3ee76b0a260177b62d290f18fd4991e9b6d25967d93004a615f88c99542b5fdeb001204e175d0155d4f0014dee79880ce4e0161bdae8e5eef6efff",
          "sha256": "68d267fa23134353199b815a9a7f7239f90a4db615febba136c7ff5b4b996bd1",
          "sha1": "baed74e3fbe086c1491ba83fb42a47ac56448c28",
          "md5": "936da3c732fe30a7966814f8904f5abd"
        }
      ]
    }
  ]
}