{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.36-test.345",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.36-test.345"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.36-test.345.aar",
          "url": "android_release-0.1.36-test.345.aar",
          "size": 1447778,
          "sha512": "095ad8958e8da749433e80ae0d3653de45c0a9edc00f18dd6c5d2594df6713d0782c6aa2d4e47889d7e5c769533e8fbd59746af32dca95dc61cbdafaf732ad71",
          "sha256": "4edde9edf2152930e7fefda9952f6e2166ef0f8ca0ac850743f603ac2b6c83c3",
          "sha1": "ff1111185bfcbd43e5c0932678cc89f415508ec5",
          "md5": "7fd9024fc2daa62698aaee2d522da7c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.36-test.345"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.36-test.345.aar",
          "url": "android_release-0.1.36-test.345.aar",
          "size": 1447778,
          "sha512": "095ad8958e8da749433e80ae0d3653de45c0a9edc00f18dd6c5d2594df6713d0782c6aa2d4e47889d7e5c769533e8fbd59746af32dca95dc61cbdafaf732ad71",
          "sha256": "4edde9edf2152930e7fefda9952f6e2166ef0f8ca0ac850743f603ac2b6c83c3",
          "sha1": "ff1111185bfcbd43e5c0932678cc89f415508ec5",
          "md5": "7fd9024fc2daa62698aaee2d522da7c4"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.36-test.345-sources.jar",
          "url": "android_release-0.1.36-test.345-sources.jar",
          "size": 374435,
          "sha512": "9064f6918ef744775aa47a92b530c7831284f9d3332643119e44bdcc2db65d7d69f4fbfa7ddc66c365e6ca5431fcda7a297d317527df73a82cb909acd3b05d5a",
          "sha256": "f91b8ff660b1298fb654ed67303981b1dcb7520116c8c5917a9be52f17324182",
          "sha1": "37141d1823d64a96505e806f8ec2db892e5dbe30",
          "md5": "9200620ef31d6e87ce4611f728a394db"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.36-test.345-javadoc.jar",
          "url": "android_release-0.1.36-test.345-javadoc.jar",
          "size": 2428343,
          "sha512": "759f4992fb2067f43caeab57e764971fe2a50f693cc481ab88ba2decec292a71ed597e63af4b09b215345b8da755cf63074a3cb9852670a1d18b703d33e20a77",
          "sha256": "0462e85862aee5d1940c982d122e6bd34ff21bf122488098acfd775bceacd49b",
          "sha1": "d8485a31de9c305713ba6ece1329afc40b066d76",
          "md5": "3b15baeb92f16702773b6693eaf6a162"
        }
      ]
    }
  ]
}