{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.21-test.275.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.21-test.275.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.21-test.275.1.aar",
          "url": "android_release-0.1.21-test.275.1.aar",
          "size": 1293897,
          "sha512": "44e410facfdc0706431aab036b661f0c2522957d28abe4c55cb0b9917c4eb6ac971091bcd7f5fc73bc4e1b2fb118c30542ba204d07fb1ef3738fcd3b0b5c841b",
          "sha256": "9962d127c5a79a1ebe7cb8d420f95f960ec01015f058412c2b9f64fb3b75330e",
          "sha1": "f0ef88ef754b391ea51aac0c71544b7226bd0ca0",
          "md5": "0cecc94a96ede0e6a90207b72ac3de0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.21-test.275.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.21-test.275.1.aar",
          "url": "android_release-0.1.21-test.275.1.aar",
          "size": 1293897,
          "sha512": "44e410facfdc0706431aab036b661f0c2522957d28abe4c55cb0b9917c4eb6ac971091bcd7f5fc73bc4e1b2fb118c30542ba204d07fb1ef3738fcd3b0b5c841b",
          "sha256": "9962d127c5a79a1ebe7cb8d420f95f960ec01015f058412c2b9f64fb3b75330e",
          "sha1": "f0ef88ef754b391ea51aac0c71544b7226bd0ca0",
          "md5": "0cecc94a96ede0e6a90207b72ac3de0a"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.21-test.275.1-sources.jar",
          "url": "android_release-0.1.21-test.275.1-sources.jar",
          "size": 324398,
          "sha512": "fc393d5ece3b02bcf093f9386612935ccaa21bdafd1984fb0149d2b02c2039feefa2c4773e90cafa07e77f4c3cc36c9d559f5fca050c4961fa6e2068db2c728e",
          "sha256": "9ff1b50a1b7e4f357338289be3c7b1f06a5d318b83c5395ec8a3828092a415bf",
          "sha1": "694568f262ec3c5fb7c9dd0f70201ca705c15ba5",
          "md5": "db13f3e73d4721f4ed299c2bd63f61b1"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.21-test.275.1-javadoc.jar",
          "url": "android_release-0.1.21-test.275.1-javadoc.jar",
          "size": 2221766,
          "sha512": "a28dda8fd6860a6a69501416be3a3749f06fd28ac0fae414682ede2e0fe0cbeddaa0308b9b94c2158e02db474dcf2742225edeb377a01c303f0e72be80da4fa2",
          "sha256": "856d476428bd364b1e4b48e7e8ccbff0f356e107238204ee96d63936216a4dc9",
          "sha1": "a890782220e3565b96442a4095de05ceccbadebe",
          "md5": "58cbbdb1fe25dd0a1d8ed40517357359"
        }
      ]
    }
  ]
}