{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.2-test.251.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.2-test.251.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.2-test.251.1.aar",
          "url": "android_release-0.1.2-test.251.1.aar",
          "size": 1244509,
          "sha512": "b4bccf99b9c521562953749958cfc26a439e2a1154ca2640ebc84d292a1ccb7989d424f7ccaaa870a37d5f33dbc2ddca21dec9f9ec8713bb9f45b6d00e87ca02",
          "sha256": "84136645be08b0d77e92856ae8f9a73a7e4991fc9f594e38a44828c98aae659f",
          "sha1": "3c8844fa454b5cd83ec58cb30f158626103fdff9",
          "md5": "61207d9e41f49b7e49da218560e28f7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.2-test.251.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.2-test.251.1.aar",
          "url": "android_release-0.1.2-test.251.1.aar",
          "size": 1244509,
          "sha512": "b4bccf99b9c521562953749958cfc26a439e2a1154ca2640ebc84d292a1ccb7989d424f7ccaaa870a37d5f33dbc2ddca21dec9f9ec8713bb9f45b6d00e87ca02",
          "sha256": "84136645be08b0d77e92856ae8f9a73a7e4991fc9f594e38a44828c98aae659f",
          "sha1": "3c8844fa454b5cd83ec58cb30f158626103fdff9",
          "md5": "61207d9e41f49b7e49da218560e28f7d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.2-test.251.1-sources.jar",
          "url": "android_release-0.1.2-test.251.1-sources.jar",
          "size": 314837,
          "sha512": "93924742f3f3ea11c37bb743d2d118a6050b0c1cc03b8e6777a010e08cc4b7cb19f6ddb60569db5f5fe84cd0fc814cd3a0e1b3c090b6d16ace48aba92aa932f4",
          "sha256": "ec22324a872ae67c3791b6818e68f1637fe6a01f21c498c4beb40cbd5044a724",
          "sha1": "56729288400fe2920dd9a35acf7fb258f0bda3e3",
          "md5": "086628d2a7226577c9002955e1fd572b"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.2-test.251.1-javadoc.jar",
          "url": "android_release-0.1.2-test.251.1-javadoc.jar",
          "size": 2133433,
          "sha512": "a3f06b6ebd3eb194310d3ffc0961c20f255eafa29b7929efa3a5d8c0303db8bef34375126a13ce45b049cd76ea1bb847aa35a25659045d43931a043f643fce91",
          "sha256": "c91e89dd51469ea59616474f72a383d6d0a0efe40cb8fdab3d4738d3c984b2b6",
          "sha1": "46d9cfb585c4ecf433276433294def0f719eb9f2",
          "md5": "890220f86e69934264ab344548ad1bd3"
        }
      ]
    }
  ]
}