{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.camerax",
    "module": "camera_android_camerax_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-1.0.aar",
          "url": "camera_android_camerax_release-1.0.aar",
          "size": 544338,
          "sha512": "bf9cb2c9fc1be9646b124cbb6bbadbc4513be6fc263bf101d63ccec4d60c31bc334da4a3c40c86733c226fa490e8e3a556e17930e66855730fe5074bd4b54743",
          "sha256": "81bc14b51bb862731ee6e32d4f0789a1312c2447343b4771019c1dc17166c21b",
          "sha1": "b47da9655f95e47809536a5c37228e4e5d167dd2",
          "md5": "20347770689b83a5a4fdd3c67a2dc33d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-core",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-camera2",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-lifecycle",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "androidx.camera",
          "module": "camera-video",
          "version": {
            "requires": "1.5.3"
          }
        },
        {
          "group": "com.google.guava",
          "module": "guava",
          "version": {
            "requires": "33.5.0-android"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "camera_android_camerax_release-1.0.aar",
          "url": "camera_android_camerax_release-1.0.aar",
          "size": 544338,
          "sha512": "bf9cb2c9fc1be9646b124cbb6bbadbc4513be6fc263bf101d63ccec4d60c31bc334da4a3c40c86733c226fa490e8e3a556e17930e66855730fe5074bd4b54743",
          "sha256": "81bc14b51bb862731ee6e32d4f0789a1312c2447343b4771019c1dc17166c21b",
          "sha1": "b47da9655f95e47809536a5c37228e4e5d167dd2",
          "md5": "20347770689b83a5a4fdd3c67a2dc33d"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-1.0-sources.jar",
          "url": "camera_android_camerax_release-1.0-sources.jar",
          "size": 92872,
          "sha512": "691f9707b3dacc78146f95f2450db1648c9318f42275c6612c2b49e21b931c626dc71131af7499387e048354cfd170d94ca486e9f30135f745f330010390c3cb",
          "sha256": "7dd8e996daf486d40065ea29e1e37b9382917ba3c44394d51a5cd7d782a70439",
          "sha1": "58ed9b15cd16c48700b39009dab4bd6d9b36e18e",
          "md5": "d11a946c3d48550ca64c2fae1863916e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "camera_android_camerax_release-1.0-javadoc.jar",
          "url": "camera_android_camerax_release-1.0-javadoc.jar",
          "size": 1117762,
          "sha512": "c7934ec3843d8f7b59765dc94dfd0588e040b576e236e28d16157ae9a8b058a652866d95f1c1c501956a6b95acca194760f086dbf9962f983b89c257b0252ad9",
          "sha256": "e925ba4dc2dc1e570ae1d97ccd742dfaebdc84b6cebd8035b63a44f015db5129",
          "sha1": "661584be0ecc80ab1e67570714704c9d310ce9ca",
          "md5": "458a8f6fc68c962113cf920b2beb301b"
        }
      ]
    }
  ]
}
