{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.share",
    "module": "share_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 18651,
          "sha512": "d01897aefadbd0b3fc7d13afb0967dddef7533cbd8aa1f29e8553530cf38ce2fb16bdf5942bd24fca2898ccbc3e011e0ee05fb5dbfaaca23b2be91fc0c5af39c",
          "sha256": "970b3186ba5feb93c17f9c3984b665f4d931278d0a6c14007098d8e4f55223c1",
          "sha1": "4d4002d36d3c6904b712aad3483e88e4f394727c",
          "md5": "ae695563c8e6e79403568f1ba401b047"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.16.0"
          }
        },
        {
          "group": "androidx.annotation",
          "module": "annotation",
          "version": {
            "requires": "1.9.1"
          }
        }
      ],
      "files": [
        {
          "name": "share_plus_release-1.0.aar",
          "url": "share_plus_release-1.0.aar",
          "size": 18651,
          "sha512": "d01897aefadbd0b3fc7d13afb0967dddef7533cbd8aa1f29e8553530cf38ce2fb16bdf5942bd24fca2898ccbc3e011e0ee05fb5dbfaaca23b2be91fc0c5af39c",
          "sha256": "970b3186ba5feb93c17f9c3984b665f4d931278d0a6c14007098d8e4f55223c1",
          "sha1": "4d4002d36d3c6904b712aad3483e88e4f394727c",
          "md5": "ae695563c8e6e79403568f1ba401b047"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_release-1.0-sources.jar",
          "url": "share_plus_release-1.0-sources.jar",
          "size": 7530,
          "sha512": "8fd42cb0575b98870f490bead8dd67fa672dc8562fc8e375e3e959d6c3428303ddf5bea3a56ec2ca61137ef1688ce1daf9700a38f2883e9fc1533a4f9f0341f4",
          "sha256": "4fc6ff44f1642ab025c792c24e412319c906950037bb2333fa3c9eaaa2214d90",
          "sha1": "72c0dfc83614bcf0785cae4c0c82fc5590688e3f",
          "md5": "8b03d5bdeab548ecd0a44f80b96e8538"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "share_plus_release-1.0-javadoc.jar",
          "url": "share_plus_release-1.0-javadoc.jar",
          "size": 283807,
          "sha512": "d9c101f21d19802f3b5d4b041e8e36b40f72ae3ed890e01c85af9ad9659b1e0f9ec6f14e14d81590bacbec8072644c72239785f6f73f2abe3c34c078b1cfe155",
          "sha256": "c53de0606e42f3564160edbd108ee7c96d6a05b0ef9477110cb866d0da69e7c1",
          "sha1": "6864c12a18d763b20aaa31368bd64c2d75cca9aa",
          "md5": "8563f971f2fcbec69fef13c347cd9935"
        }
      ]
    }
  ]
}
