{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.14"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 112155,
          "sha512": "9005bcf11f3fa6227b0044080241bedd670732cccaab0501bccfd9bac192f6c400253e67468e612d7c131740662846c986d4b564a24d118ddd609370005abbf6",
          "sha256": "8323a8ab6a41d85e6c0192f557ac7e8f5e223bab1ca6ce3a5c309fae2d84a220",
          "sha1": "51de7703412e8175e7652aa34715e5d7e525477f",
          "md5": "b93d8d6281019574ffc87dfb732ffa85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-59aa584fdf100e6c78c785d8a5b565d1de4b48ab"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.20"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 112155,
          "sha512": "9005bcf11f3fa6227b0044080241bedd670732cccaab0501bccfd9bac192f6c400253e67468e612d7c131740662846c986d4b564a24d118ddd609370005abbf6",
          "sha256": "8323a8ab6a41d85e6c0192f557ac7e8f5e223bab1ca6ce3a5c309fae2d84a220",
          "sha1": "51de7703412e8175e7652aa34715e5d7e525477f",
          "md5": "b93d8d6281019574ffc87dfb732ffa85"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-sources.jar",
          "url": "shared_preferences_android_release-1.0-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-javadoc.jar",
          "url": "shared_preferences_android_release-1.0-javadoc.jar",
          "size": 358386,
          "sha512": "93a247a12e29e5188b7680773ad4c5ccd1c5f07e61ac5a041baed368b61c280f0c391b3ac7a5e922809c9a6e99a8110b5e4420d0c6f80d808cf7f98828d7fcc7",
          "sha256": "677fd94f1f05b574730db8d25a298566aea701f4207abf5e4780873302da4455",
          "sha1": "6451b5003a952f9b33ec75136150a20176ddc8f7",
          "md5": "560c3d800638f6aa1168b9631e13e002"
        }
      ]
    }
  ]
}
