{
  "formatVersion": "1.1",
  "component": {
    "group": "io.flutter.plugins.sharedpreferences",
    "module": "shared_preferences_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 108977,
          "sha512": "713cf08bd1a822f7571bb9be9ca9e9c3fa9f323ae649c626f23c003fd96c99c64bf8280b892eb3c3e4f01b99015783cccc9144b8b20f3c31c15552f2fde21456",
          "sha256": "ae46dfbea699e342ec7d4b4c855335a64831cc067767ec6b7111e1de9e4ce152",
          "sha1": "b27e87c9a48747ace90f3493ed217eb75195c0b4",
          "md5": "e6161f9300aafccea5f026c742e369d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.datastore",
          "module": "datastore-preferences",
          "version": {
            "requires": "1.1.7"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.1.0"
          }
        }
      ],
      "files": [
        {
          "name": "shared_preferences_android_release-1.0.aar",
          "url": "shared_preferences_android_release-1.0.aar",
          "size": 108977,
          "sha512": "713cf08bd1a822f7571bb9be9ca9e9c3fa9f323ae649c626f23c003fd96c99c64bf8280b892eb3c3e4f01b99015783cccc9144b8b20f3c31c15552f2fde21456",
          "sha256": "ae46dfbea699e342ec7d4b4c855335a64831cc067767ec6b7111e1de9e4ce152",
          "sha1": "b27e87c9a48747ace90f3493ed217eb75195c0b4",
          "md5": "e6161f9300aafccea5f026c742e369d3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-sources.jar",
          "url": "shared_preferences_android_release-1.0-sources.jar",
          "size": 13712,
          "sha512": "2322077f316271d516b7a13c1a85aab6581228ea0e162c453224193ad43483785f75aff62fc6c4caf84db7bca653741e6c511789c8e80002dcbafdbe69b365a4",
          "sha256": "795cd668a3c81d21d93904f0d9577010f5d39a9a6a20b0c527bd78f1930961e7",
          "sha1": "aca57cb05a8d494b755f349cc32a2cfa18ea7165",
          "md5": "e01671777e4470c08cf818f20d90a1fd"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "shared_preferences_android_release-1.0-javadoc.jar",
          "url": "shared_preferences_android_release-1.0-javadoc.jar",
          "size": 358388,
          "sha512": "82810190bbe4a8e666cdbaa5c8127ba4caf9d8001591efa56590e407be3becfe4f7018bfcab311524b7bc952fa273b0f931fd51e57d090b0050a006ef3f5cd13",
          "sha256": "ee94bf4afae4a2aab89e54141dbbfdd8a8653324be6cc1644069aeedaf51cc03",
          "sha1": "7196fb3073e2059c88c451e62bc59a811dd9f17f",
          "md5": "02869046e484633f0698a27f770ab30e"
        }
      ]
    }
  ]
}
