{
  "formatVersion": "1.1",
  "component": {
    "group": "vn.hunghd.flutter.plugins.imagecropper",
    "module": "image_cropper_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "image_cropper_release-1.0.aar",
          "url": "image_cropper_release-1.0.aar",
          "size": 12522,
          "sha512": "5ee9b35569985944065c35b379a8b1bccbf42a0d2f4564a2b646b6336defac0ef60a03141d195ab431f15cd64e2859dc05b69882536f924061213de3db79c8cc",
          "sha256": "05bdcf575e7ea045e189ec5d617c317015aab56f0a059499c38061fc44f2634d",
          "sha1": "48ff1abc125e20eb77b9a0e651dd2a78bf7f34f6",
          "md5": "148fc1f820959058f2a8f4c22e563788"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "com.github.yalantis",
          "module": "ucrop",
          "version": {
            "requires": "2.2.10"
          }
        },
        {
          "group": "androidx.preference",
          "module": "preference",
          "version": {
            "requires": "1.2.1"
          }
        }
      ],
      "files": [
        {
          "name": "image_cropper_release-1.0.aar",
          "url": "image_cropper_release-1.0.aar",
          "size": 12522,
          "sha512": "5ee9b35569985944065c35b379a8b1bccbf42a0d2f4564a2b646b6336defac0ef60a03141d195ab431f15cd64e2859dc05b69882536f924061213de3db79c8cc",
          "sha256": "05bdcf575e7ea045e189ec5d617c317015aab56f0a059499c38061fc44f2634d",
          "sha1": "48ff1abc125e20eb77b9a0e651dd2a78bf7f34f6",
          "md5": "148fc1f820959058f2a8f4c22e563788"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_cropper_release-1.0-sources.jar",
          "url": "image_cropper_release-1.0-sources.jar",
          "size": 6826,
          "sha512": "299e93d217e219cddddf6dfcda5f59af3272f345c9a4db7c2beddc41875ad8d3dd3462a00d2963f370ffd2afa3c0e86917f5cb0694591098e8115f9f8035245d",
          "sha256": "aace2ca8204ffac7687073b7227fb1cd9ae7c63aa4d091f04efa633709e0aa31",
          "sha1": "f41e521bbe4630101e31051e23d49390c7a853c2",
          "md5": "060d0986acc0d932b6e10d03a8e98efb"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "image_cropper_release-1.0-javadoc.jar",
          "url": "image_cropper_release-1.0-javadoc.jar",
          "size": 269829,
          "sha512": "4d1008b4c97f73b50dd742b87f21bb93e4aff933963a31abc7cc3ff0eef3e1920c3287a319adbba82f1ba016e5106850502f4dc04c95aafd67d579b5e3a3cdf5",
          "sha256": "27898982a47fcef7f2f19754eb2ed6d82ee4cf75431bbd314bbb8045c8dba0d1",
          "sha1": "fdf9d7a88ee195a07186322e7e2798655df442a6",
          "md5": "5954c942b3a5a026f81e0d159dd25598"
        }
      ]
    }
  ]
}
