{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.19-test.330",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.19-test.330"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.19-test.330.aar",
          "url": "android_release-0.1.19-test.330.aar",
          "size": 1411084,
          "sha512": "038b858f7688bd8cd53bbbcdf3a19ac1f4135027e7cbd09c86bbf6db0f5f6e67142e846709d7af67f92df664c2e9819b8349f27bedbe07cf927d9d9b45f68a28",
          "sha256": "589e23ddc812d77bfb331492e7259aa155e28e761ec3743a96f93b5d794fc3be",
          "sha1": "6434a424b4fb3c6205167dbd47ff2889f3e9dd07",
          "md5": "0203b95af3a2135ca397ed66c8733e94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.19-test.330"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.19-test.330.aar",
          "url": "android_release-0.1.19-test.330.aar",
          "size": 1411084,
          "sha512": "038b858f7688bd8cd53bbbcdf3a19ac1f4135027e7cbd09c86bbf6db0f5f6e67142e846709d7af67f92df664c2e9819b8349f27bedbe07cf927d9d9b45f68a28",
          "sha256": "589e23ddc812d77bfb331492e7259aa155e28e761ec3743a96f93b5d794fc3be",
          "sha1": "6434a424b4fb3c6205167dbd47ff2889f3e9dd07",
          "md5": "0203b95af3a2135ca397ed66c8733e94"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.19-test.330-sources.jar",
          "url": "android_release-0.1.19-test.330-sources.jar",
          "size": 359024,
          "sha512": "dbf5bc96206ad97424dabd09ccaa091d07bd5ffcaac4fb2a50df1933a6329085757a42586bb0242bb89756be8c928e4761886bab6b1de9eaec70bd4073e0686e",
          "sha256": "1657fa4548f52e6f61d85f4f0aeb5c37b74bd31c9cd1d41a847749449a52e314",
          "sha1": "210151cd05ac3479b10a7a820dbcbb16b6e385c6",
          "md5": "13e66bd3a325d4e5ecdecd1185178742"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.19-test.330-javadoc.jar",
          "url": "android_release-0.1.19-test.330-javadoc.jar",
          "size": 2409020,
          "sha512": "5e26cd901e3409aee1e77e6047f40b34cdb2915d0b1e6e09fd3d6e1a7cdac98f25361b2b1d5daee491b55c92e2ecc2232628d2b1ba6dfb29948efd8793831c83",
          "sha256": "836a9bd0ad5db676064667cfa57be28ca31e4fbecb9eb571196e4bdb96c41894",
          "sha1": "88bbe22220b1894be5182edeee83425b0650cb61",
          "md5": "f07ccdbbd9b988f42aa0a4d1384d5d81"
        }
      ]
    }
  ]
}