{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.7-test.232.1",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.7-test.232.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.7-test.232.1.aar",
          "url": "android_release-0.1.7-test.232.1.aar",
          "size": 1225843,
          "sha512": "13405587830496f9cafd80b387900b1478efaba0099f3d53f54669182b2604b1a098ec658ac9fb32767d086e40450f99572c690ae3b79cbedb50baa80b503537",
          "sha256": "de0db163020e687e0645b2c4be3df256b1020b6db84e79c63fa84929fdfa262c",
          "sha1": "dbdc16b8e9e24fc42282240f7cad3c78ef376272",
          "md5": "125537d8e7ffb4cb41a0d43f3642c1cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.7-test.232.1"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.7-test.232.1.aar",
          "url": "android_release-0.1.7-test.232.1.aar",
          "size": 1225843,
          "sha512": "13405587830496f9cafd80b387900b1478efaba0099f3d53f54669182b2604b1a098ec658ac9fb32767d086e40450f99572c690ae3b79cbedb50baa80b503537",
          "sha256": "de0db163020e687e0645b2c4be3df256b1020b6db84e79c63fa84929fdfa262c",
          "sha1": "dbdc16b8e9e24fc42282240f7cad3c78ef376272",
          "md5": "125537d8e7ffb4cb41a0d43f3642c1cc"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.7-test.232.1-sources.jar",
          "url": "android_release-0.1.7-test.232.1-sources.jar",
          "size": 311995,
          "sha512": "cb6834355354bd364502390a6032a2c02d2505e3072f5961c716066bd7651272c899a88137ce239dad81e0c3f75156e6ef95377500820db60c2179be48c83343",
          "sha256": "774d562801e9441d57fc640320268eab756415ce9e91829f7fa977c517d08d6d",
          "sha1": "257444509b0fb9dfc883ec79cc074f2c789b1411",
          "md5": "90c50015c0cde24e5665a47e6cd3d8a0"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.7-test.232.1-javadoc.jar",
          "url": "android_release-0.1.7-test.232.1-javadoc.jar",
          "size": 2108836,
          "sha512": "ffdd9fda0e0f36ee2b4dda49a8aa39e0922aa39094a1997506d0d634358cd4e36160ee8e5cf60430fb523e0cd6cf9e6cf226766afb5ac431239a35839372df78",
          "sha256": "dde4914ff7c38b908fb65ede55cbb5bff20b3b25d43a69dec0477634438c5fbe",
          "sha1": "a12980da4217d886b47ac170ffe4af78c3a2c052",
          "md5": "8c1bd95f39db1ab78c5c4fcbd5cce8e0"
        }
      ]
    }
  ]
}