{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "android_release",
    "version": "0.1.14-test.283",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.11.1"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.14-test.283"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.14-test.283.aar",
          "url": "android_release-0.1.14-test.283.aar",
          "size": 1328221,
          "sha512": "2d18170fff1524ce5dc42c2536580d400f3bebfd524bb9d7a6494887a57b433ce0def5ba5ce10df2ab582d43535ebcadb8acacc9ef428a12c56af950ec3944cf",
          "sha256": "48164d9e6ebdec1f687eea30e03482589647b4db289cff401781a33e17bc5126",
          "sha1": "6d18d8cffbc53ea4d4cbefe12a98a7ccda21de6e",
          "md5": "caa149f49c108c4e19921430b0aa73ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "2.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core-ktx",
          "version": {
            "requires": "1.13.1"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.3.0"
          }
        },
        {
          "group": "androidx.health.connect",
          "module": "connect-client",
          "version": {
            "requires": "1.2.0-alpha02"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-android",
          "version": {
            "requires": "1.7.3"
          }
        },
        {
          "group": "org.jetbrains.kotlinx",
          "module": "kotlinx-coroutines-core",
          "version": {
            "requires": "1.10.2"
          }
        },
        {
          "group": "com.google.dagger",
          "module": "hilt-android",
          "version": {
            "requires": "2.57.1"
          }
        },
        {
          "group": "no.nordicsemi.android",
          "module": "dfu",
          "version": {
            "requires": "2.9.0"
          }
        },
        {
          "group": "com.rolla.sdk",
          "module": "flutter_release",
          "version": {
            "requires": "0.1.14-test.283"
          }
        },
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "android_release-0.1.14-test.283.aar",
          "url": "android_release-0.1.14-test.283.aar",
          "size": 1328221,
          "sha512": "2d18170fff1524ce5dc42c2536580d400f3bebfd524bb9d7a6494887a57b433ce0def5ba5ce10df2ab582d43535ebcadb8acacc9ef428a12c56af950ec3944cf",
          "sha256": "48164d9e6ebdec1f687eea30e03482589647b4db289cff401781a33e17bc5126",
          "sha1": "6d18d8cffbc53ea4d4cbefe12a98a7ccda21de6e",
          "md5": "caa149f49c108c4e19921430b0aa73ec"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.14-test.283-sources.jar",
          "url": "android_release-0.1.14-test.283-sources.jar",
          "size": 334343,
          "sha512": "3f10614e514c9d84b1187e15a6187e069faa8576c24367568ea6f201e15bd06d8c269dd9b53c6053328256b7675221911bc1e22f5be8580289f41383be9f8c9d",
          "sha256": "28182b74ede832a1e8ae65b68704fc895db61364a4dce049a964ddc33de517bb",
          "sha1": "c0b68384db17ee8e72b14226b4539d191975deff",
          "md5": "b3f2f94b10ec7fb79f9615b1c1803f5e"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "android_release-0.1.14-test.283-javadoc.jar",
          "url": "android_release-0.1.14-test.283-javadoc.jar",
          "size": 2286572,
          "sha512": "3b2d651e0666e046a13d96a32f77d8babd34b701f88218e68759d92d3cc628a5b2038f1c3432809ed5e7ffef81c2e86c5c70b5baadc4675461463b481a4021ad",
          "sha256": "a67563805e2a07ab0f7e5a4c12c0b87dc7ee164734f422187946d870627bbe15",
          "sha1": "d61bb1ff80a4ec44b02dc7133cb199d9dbc8a553",
          "md5": "d876574d4f263b3acc4fd86d7135e23b"
        }
      ]
    }
  ]
}