{
  "formatVersion": "1.1",
  "component": {
    "group": "com.rolla.sdk",
    "module": "flutter_release",
    "version": "0.1.25-test.336",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mohamednagdy.flutter_native_timezone_latest",
          "module": "flutter_native_timezone_latest_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.geolocator",
          "module": "geolocator_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "vn.hunghd.flutter.plugins.imagecropper",
          "module": "image_cropper_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mapbox.maps.mapbox_maps",
          "module": "mapbox_maps_flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.wakelock",
          "module": "wakelock_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.1.25-test.336.aar",
          "url": "flutter_release-0.1.25-test.336.aar",
          "size": 21423447,
          "sha512": "4190412e45fd0b18e2f91c85a7972d26d0dd177e39a9d7fe5aa2175621befa045a4ad37e64bc8249ee5a183106b32c56671fdcaa3563edda4f56cd23e4dad9c8",
          "sha256": "679cbab51fd6f9c31a7095ae0f8cf18475adf5dd3e668d3fa6709b6d9f74ea12",
          "sha1": "25e76f1d13f741a2455a398302c7b844ea033026",
          "md5": "ee04f92061c3119e758ebef147f6c5ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "armeabi_v7a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "arm64_v8a_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "io.flutter",
          "module": "x86_64_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.connectivity",
          "module": "connectivity_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.device_info",
          "module": "device_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.lib.flutter_blue_plus",
          "module": "flutter_blue_plus_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.dexterous.flutterlocalnotifications",
          "module": "flutter_local_notifications_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mohamednagdy.flutter_native_timezone_latest",
          "module": "flutter_native_timezone_latest_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.flutter_plugin_android_lifecycle",
          "module": "flutter_plugin_android_lifecycle_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.it_nomads.fluttersecurestorage",
          "module": "flutter_secure_storage_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.geolocator",
          "module": "geolocator_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "cachet.plugins.health",
          "module": "health_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "vn.hunghd.flutter.plugins.imagecropper",
          "module": "image_cropper_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.imagepicker",
          "module": "image_picker_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni",
          "module": "jni_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.github.dart_lang.jni_flutter",
          "module": "jni_flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.mapbox.maps.mapbox_maps",
          "module": "mapbox_maps_flutter_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.packageinfo",
          "module": "package_info_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.baseflow.permissionhandler",
          "module": "permission_handler_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.share",
          "module": "share_plus_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.sharedpreferences",
          "module": "shared_preferences_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "com.tekartik.sqflite",
          "module": "sqflite_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.urllauncher",
          "module": "url_launcher_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "io.flutter.plugins.videoplayer",
          "module": "video_player_android_release",
          "version": {
            "requires": "1.0"
          }
        },
        {
          "group": "dev.fluttercommunity.plus.wakelock",
          "module": "wakelock_plus_release",
          "version": {
            "requires": "1.0"
          }
        }
      ],
      "files": [
        {
          "name": "flutter_release-0.1.25-test.336.aar",
          "url": "flutter_release-0.1.25-test.336.aar",
          "size": 21423447,
          "sha512": "4190412e45fd0b18e2f91c85a7972d26d0dd177e39a9d7fe5aa2175621befa045a4ad37e64bc8249ee5a183106b32c56671fdcaa3563edda4f56cd23e4dad9c8",
          "sha256": "679cbab51fd6f9c31a7095ae0f8cf18475adf5dd3e668d3fa6709b6d9f74ea12",
          "sha1": "25e76f1d13f741a2455a398302c7b844ea033026",
          "md5": "ee04f92061c3119e758ebef147f6c5ed"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.1.25-test.336-sources.jar",
          "url": "flutter_release-0.1.25-test.336-sources.jar",
          "size": 1731,
          "sha512": "65edc9054dfefd60be6bf5d198ef321ddb714193509f678b2167a8236afdc50e78018a541ff2419f9a702408274a22f708284154b9b27a9784f2bb0eca69419c",
          "sha256": "7f36aa4025778e534b15dbf720e73e6cb84a8a9f5efdb50fe4840b7fe270dc23",
          "sha1": "a3403e979c28b6aaaa106f2bec273d5eafec14c5",
          "md5": "c62d0e79b4517db47e0acba580a1f110"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "flutter_release-0.1.25-test.336-javadoc.jar",
          "url": "flutter_release-0.1.25-test.336-javadoc.jar",
          "size": 261616,
          "sha512": "5b64cd42625ec2c75c9437f18bd3e5c69969556ad3c068ca7bd0242f8c7d23ce6c65d2f8097e005e229d5f241d05929b5c0bf94caa334d45fd2f8e456b2c347f",
          "sha256": "3c5197d7e5a0df80632c6be2dcc3d32fe22a7c0acd3b7be2fa4d01973e5759b0",
          "sha1": "acd5578a961c4af43f01bb0d35115becc8c2d530",
          "md5": "4fdbf6eb2ad0e81958a11cf3a2e9d327"
        }
      ]
    }
  ]
}
