{
  "formatVersion": "1.1",
  "component": {
    "group": "dev.fluttercommunity.plus.packageinfo",
    "module": "package_info_plus_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 5912,
          "sha512": "12952471061dcc1dce31b4d3a749e685819f7024aa86fab60189b5b0598b2af2334730663b78839aaaae20a4bacfc1b694276022be39cd970a13f6e843c1f877",
          "sha256": "74d813b268e2caafd12878053297be94bfe7c1af4b696922081820e6668662b6",
          "sha1": "7f4d545eace18925875da63cae963d1055812da1",
          "md5": "06f7d5d754603a9090614e4367d42d32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "org.jetbrains.kotlin",
          "module": "kotlin-stdlib",
          "version": {
            "requires": "1.7.22"
          }
        }
      ],
      "files": [
        {
          "name": "package_info_plus_release-1.0.aar",
          "url": "package_info_plus_release-1.0.aar",
          "size": 5912,
          "sha512": "12952471061dcc1dce31b4d3a749e685819f7024aa86fab60189b5b0598b2af2334730663b78839aaaae20a4bacfc1b694276022be39cd970a13f6e843c1f877",
          "sha256": "74d813b268e2caafd12878053297be94bfe7c1af4b696922081820e6668662b6",
          "sha1": "7f4d545eace18925875da63cae963d1055812da1",
          "md5": "06f7d5d754603a9090614e4367d42d32"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-1.0-sources.jar",
          "url": "package_info_plus_release-1.0-sources.jar",
          "size": 2693,
          "sha512": "baaae2e6245030a7de70f19e43504fb87d6d374ec50af2dd23321d0ab0bf43dbb918967f0b66277e2662ccb4faf2098ffcb870dd1e597bc1dc8ac730e9c7b5fb",
          "sha256": "3f208ebbb8c9b93761dea623949b7ee1a9cd74e818acede7ccc4f562f3839a5d",
          "sha1": "12df81060cfa11fc35581f9c91da8922a5f8e6f0",
          "md5": "f30e01eabb60c79316840a3ed7edecb3"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "package_info_plus_release-1.0-javadoc.jar",
          "url": "package_info_plus_release-1.0-javadoc.jar",
          "size": 265020,
          "sha512": "0f22897288c56a20a74784d59ec2c31a1cd32a73115f9baea692a10c2d531af3235b4c1114d25869f6a7cedb5f4fbe4ff319649e1800cb96e2a4e4b1e31d660e",
          "sha256": "dd156d33dbb65caa617edd4661365178b9892e87d83b1880c8411f156ef48266",
          "sha1": "e8ee8a96464e45d8ab37512304ef3d75264758f9",
          "md5": "519514f0cc18d4154e6ac8b163f353f1"
        }
      ]
    }
  ]
}
