{
  "formatVersion": "1.1",
  "component": {
    "group": "com.baseflow.geolocator",
    "module": "geolocator_android_release",
    "version": "1.0",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "8.12"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_release-1.0.aar",
          "url": "geolocator_android_release-1.0.aar",
          "size": 57635,
          "sha512": "da5f0f019e09d662c6d8a8dd3bf754978b229cc0c5f00a48694a27c97dcb0d8f3c37ae1b3962fbf7006372e0b37c375c24dd8b87d92f9f5ceaf5bf1c9aca04f4",
          "sha256": "fa17010316a8509f4c6e50faaac24cd361994e88bbb8119830a013e86756b507",
          "sha1": "72a97717a6d5c5c5dcdc8ab0f60f5d2984ffdd50",
          "md5": "81abaf8cd3a50f3567007a9627730ac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "dependencies": [
        {
          "group": "io.flutter",
          "module": "flutter_embedding_release",
          "version": {
            "requires": "1.0.0-d2913632a4578ee4d0b8b1c4a69888c8a0672c4b"
          }
        },
        {
          "group": "com.google.android.gms",
          "module": "play-services-location",
          "version": {
            "requires": "21.2.0"
          }
        },
        {
          "group": "androidx.core",
          "module": "core",
          "version": {
            "requires": "1.13.0"
          }
        }
      ],
      "files": [
        {
          "name": "geolocator_android_release-1.0.aar",
          "url": "geolocator_android_release-1.0.aar",
          "size": 57635,
          "sha512": "da5f0f019e09d662c6d8a8dd3bf754978b229cc0c5f00a48694a27c97dcb0d8f3c37ae1b3962fbf7006372e0b37c375c24dd8b87d92f9f5ceaf5bf1c9aca04f4",
          "sha256": "fa17010316a8509f4c6e50faaac24cd361994e88bbb8119830a013e86756b507",
          "sha1": "72a97717a6d5c5c5dcdc8ab0f60f5d2984ffdd50",
          "md5": "81abaf8cd3a50f3567007a9627730ac6"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseSourcePublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "sources",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geolocator_android_release-1.0-sources.jar",
          "url": "geolocator_android_release-1.0-sources.jar",
          "size": 31879,
          "sha512": "f3f291e3d9e888c3dd99f09f83d3a9ec1a485a3238bb9d034aa374286ae84ec2522203afb28e4568fbf59b2a2fb42db9efd99b085e5bc44655da26e73aa31043",
          "sha256": "3c1c46f21e9c253012e2d51ae8d26cb8cba7c953849ce596df03d12f8ffe5a50",
          "sha1": "673e2dadde3fc356791a4c3b67f20cf607a2761b",
          "md5": "40d46bc156ff183cfbd6bf092c066005"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseJavaDocPublication",
      "attributes": {
        "org.gradle.category": "documentation",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.docstype": "javadoc",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "geolocator_android_release-1.0-javadoc.jar",
          "url": "geolocator_android_release-1.0-javadoc.jar",
          "size": 389576,
          "sha512": "494584e38de2c264303c4ad36b3028f66be2ab3ba0aa20baf5b44c6edfb3feb807ea807f9adfd47585b603a6b6b975b85e45e32a792dda31f65077b9e8aabefe",
          "sha256": "037011f4619f5a471ac96451a2056353eaf59092033731288e36b36fe0888f09",
          "sha1": "ce43fa405a31c7387f31012d9cb97e1c6580f220",
          "md5": "13d8e19a9294795372ae43a265e38e0c"
        }
      ]
    }
  ]
}
